In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Three-Way Entity Resolution: TKPI + MyFCD + USDA
Konversi dari notebook entity_resolution_threeway.ipynb ke skrip Python.
 
Cara pakai:
  1. Sesuaikan BASE, TKPI_PATH, MYFCD_PATH, dan OUTPUT_DIR di bagian PATHS.
  2. Jalankan:  python entity_resolution_threeway.py
"""
"""
Three-Way Entity Resolution: TKPI + MyFCD + USDA
=================================================
Links Southeast Asian food items (TKPI, MyFCD) to their closest
USDA SR Legacy equivalents so that USDA nutrient values can be
borrowed to fill schema gaps (magnesium, total sugars, saturated fat,
cholesterol, vitamin B6, vitamin B12).
 
Pipeline
--------
Step 1 : Category crosswalk  — map each regional category to USDA categories
Step 2 : Text normalisation  — clean food names, keep English translations
Step 3 : TF-IDF cosine match — score similarity within category blocks
Step 4 : Confidence labelling — HIGH / MEDIUM / LOW per match
Step 5 : Borrowing policy    — decide what to borrow based on confidence
Step 6 : Value borrowing     — pull USDA nutrient values into the linked records
 
Usage
-----
Set BASE, TKPI_PATH, MYFCD_PATH to your local paths, then run:
    python entity_resolution.py
"""
 
import pandas as pd
import numpy as np
import re
from collections import Counter
 
# ─────────────────────────────────────────────────────────────────────────────
# 0. PATHS  ── adjust to your folder layout
# ─────────────────────────────────────────────────────────────────────────────
BASE       = r"C:\Users\intan\OneDrive\Documents\Intan\02\2026\Jatim Melaju\Dataset\USDA\FoodDataLegacy2018"
TKPI_PATH  = r"C:\Users\intan\OneDrive\Documents\Intan\02\2026\Jatim Melaju\Dataset\GitHub\food-nutrition\data_clean\tkpi_clean.csv"
MYFCD_PATH = r"C:\Users\intan\OneDrive\Documents\Intan\02\2026\Jatim Melaju\Dataset\GitHub\food-nutrition\data_clean\myfcd_clean.csv"
 
# Folder tempat menyimpan semua output CSV (ubah bila perlu; default = folder USDA/BASE)
import os
OUTPUT_DIR = BASE
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [2]:
# ─────────────────────────────────────────────────────────────────────────────
# 1. LOAD DATA
# ─────────────────────────────────────────────────────────────────────────────
tkpi  = pd.read_csv(TKPI_PATH)
myfcd = pd.read_csv(MYFCD_PATH)
 
usda  = pd.read_csv(f"{BASE}/food.csv")
ucat  = pd.read_csv(f"{BASE}/food_category.csv")
usda  = usda.merge(
    ucat[["id", "description"]].rename(
        columns={"id": "food_category_id", "description": "usda_category"}
    ),
    on="food_category_id", how="left"
)
 
food_nutrient = pd.read_csv(f"{BASE}/food_nutrient.csv")
nutrient_meta = pd.read_csv(f"{BASE}/nutrient.csv")

In [3]:
# ─────────────────────────────────────────────────────────────────────────────
# 2. CATEGORY CROSSWALK
#    Each regional category maps to one or more USDA categories.
#    Purpose: restrict TF-IDF matching to foods of the same food group
#             (called "blocking") so we don't compare vegetables with meats.
# ─────────────────────────────────────────────────────────────────────────────
CROSSWALK_TKPI = {
    "serealia":              ["Cereal Grains and Pasta", "Baked Products",
                              "Breakfast Cereals"],
    "sayuran":               ["Vegetables and Vegetable Products"],
    "buah":                  ["Fruits and Fruit Juices"],
    "daging":                ["Beef Products", "Pork Products",
                              "Lamb, Veal, and Game Products",
                              "Poultry Products", "Sausages and Luncheon Meats"],
    "ikan/kerang/udang dll": ["Finfish and Shellfish Products"],
    "kacang-kacangan":       ["Legumes and Legume Products", "Nut and Seed Products"],
    "umbi berpati":          ["Vegetables and Vegetable Products",
                              "Cereal Grains and Pasta"],
    "telur":                 ["Dairy and Egg Products"],
    "susu":                  ["Dairy and Egg Products"],
    "minyak/lemak":          ["Fats and Oils"],
    "bumbu":                 ["Spices and Herbs", "Soups, Sauces, and Gravies"],
    "minuman non alkohol":   ["Beverages"],
    "konfeksioneri":         ["Sweets", "Snacks"],
}
 
CROSSWALK_MYFCD = {
    "cereals and grain products":          ["Cereal Grains and Pasta", "Baked Products"],
    "rice and rice flour based":           ["Cereal Grains and Pasta"],
    "wheat flour based":                   ["Baked Products", "Cereal Grains and Pasta"],
    "cereal based":                        ["Breakfast Cereals", "Cereal Grains and Pasta"],
    "glutinous rice based":                ["Cereal Grains and Pasta"],
    "vegetables and vegetable products":   ["Vegetables and Vegetable Products"],
    "vegetable dishes":                    ["Vegetables and Vegetable Products",
                                            "Soups, Sauces, and Gravies"],
    "vegetables and fruits based":         ["Vegetables and Vegetable Products",
                                            "Fruits and Fruit Juices"],
    "fruits and fruit products":           ["Fruits and Fruit Juices"],
    "meat and meat products":              ["Beef Products", "Pork Products",
                                            "Poultry Products",
                                            "Lamb, Veal, and Game Products"],
    "meat dishes":                         ["Beef Products", "Pork Products",
                                            "Poultry Products"],
    "fish, shellfish and products":        ["Finfish and Shellfish Products"],
    "fish and sea-food dishes":            ["Finfish and Shellfish Products"],
    "legumes and legume products":         ["Legumes and Legume Products"],
    "legume based":                        ["Legumes and Legume Products"],
    "nuts, seeds and products":            ["Nut and Seed Products"],
    "eggs":                                ["Dairy and Egg Products"],
    "milk and milk products":              ["Dairy and Egg Products"],
    "oils and fats":                       ["Fats and Oils"],
    "sugars and syrups":                   ["Sweets"],
    "beverages":                           ["Beverages"],
    "starchy roots, tubers and products":  ["Vegetables and Vegetable Products"],
    "tuber based":                         ["Vegetables and Vegetable Products"],
    "porridge and ipengat/i":              ["Cereal Grains and Pasta",
                                            "Breakfast Cereals"],
    "miscellaneous":                       ["Soups, Sauces, and Gravies",
                                            "Spices and Herbs",
                                            "Meals, Entrees, and Side Dishes"],
}

In [4]:
# ─────────────────────────────────────────────────────────────────────────────
# 3. TEXT NORMALISATION
#    KEY DESIGN DECISION: keep parentheses content.
#    TKPI names follow the pattern  "Bahasa name (English name)"
#    e.g. "kacang arab, kering (chick pea, raw)"
#    Removing the brackets discards the English translation, which is the
#    only part that overlaps with USDA names. We keep it.
# ─────────────────────────────────────────────────────────────────────────────
STOPWORDS = {
    # English generic food-state words
    "raw", "cooked", "dried", "dry", "fresh", "canned", "frozen", "boiled",
    "grilled", "fried", "baked", "steamed", "smoked", "salted", "roasted",
    "per", "100g", "and", "or", "with", "the", "in", "of", "a", "an",
    "mature", "seeds", "products", "food", "foods", "grade", "whole",
    # Bahasa generic food-state words
    "mentah", "kering", "goreng", "rebus", "segar", "dan",
    "masak", "matang", "olahan", "panggang",
}
 
def normalize_name(text: str) -> str:
    """
    Lowercase → open brackets → remove punctuation → strip stopwords.
    Keeps English translations embedded in TKPI/MyFCD names.
    """
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"[()\/,]", " ", text)   # open brackets and slashes
    text = re.sub(r"[^a-z\s]", " ", text)  # remove non-alpha
    tokens = [w for w in text.split()
              if w not in STOPWORDS and len(w) > 2]
    return " ".join(tokens)
 
tkpi ["name_norm"] = tkpi ["food_name_normalized"].apply(normalize_name)
myfcd["name_norm"] = myfcd["food_name_normalized"].apply(normalize_name)
usda ["name_norm"] = usda ["description"].apply(normalize_name)

In [5]:
# ─────────────────────────────────────────────────────────────────────────────
# 4. TF-IDF COSINE SIMILARITY  (pure numpy — no sklearn required)
#    Why TF-IDF?  It up-weights rare, specific food terms (e.g. "arrowroot",
#    "rambutan") and down-weights common ones (e.g. "bean", "oil"),
#    giving more meaningful similarity scores than simple word overlap.
# ─────────────────────────────────────────────────────────────────────────────
def tfidf_cosine_match(
    query_names:  list,   # food names to match (TKPI or MyFCD block)
    corpus_names: list,   # candidate pool (USDA block)
    corpus_ids:   list,   # USDA fdc_id for each corpus entry
    top_n: int = 3        # return top-n candidates per query
) -> list:
    """
    Returns list of (query_index, usda_fdc_id, cosine_score) tuples.
    """
    all_docs  = query_names + corpus_names
    n_query   = len(query_names)
    tokenized = [d.split() for d in all_docs]
 
    # Build vocabulary from all documents in this block
    vocab     = sorted({w for doc in tokenized for w in doc})
    word_idx  = {w: i for i, w in enumerate(vocab)}
    V         = len(vocab)
 
    # Term Frequency matrix
    tf = np.zeros((len(all_docs), V), dtype=np.float32)
    for di, doc in enumerate(tokenized):
        cnt = Counter(doc)
        for w, c in cnt.items():
            if w in word_idx:
                tf[di, word_idx[w]] = c / max(len(doc), 1)
 
    # Inverse Document Frequency  (smoothed)
    df   = (tf > 0).sum(axis=0)
    idf  = np.log((len(all_docs) + 1) / (df + 1)) + 1
 
    # TF-IDF matrix, L2-normalised (so dot product = cosine similarity)
    tfidf      = tf * idf
    norms      = np.linalg.norm(tfidf, axis=1, keepdims=True)
    norms[norms == 0] = 1
    tfidf_norm = tfidf / norms
 
    # Cosine similarity: queries × corpus
    Q   = tfidf_norm[:n_query]
    C   = tfidf_norm[n_query:]
    sim = Q @ C.T                 # shape: (n_query, n_corpus)
 
    results = []
    for qi in range(n_query):
        top_idx = np.argsort(sim[qi])[::-1][:top_n]
        for ci in top_idx:
            results.append((qi, corpus_ids[ci], float(sim[qi, ci])))
    return results

In [23]:
# ─────────────────────────────────────────────────────────────────────────────
# 5. CATEGORY-BLOCKED MATCHING
#    We only compare foods within the same mapped category block.
#    This is called "blocking" in record-linkage literature — it reduces
#    complexity from O(n×m) to O(n_block × m_block) and improves precision.
# ─────────────────────────────────────────────────────────────────────────────
def match_to_usda(
    source_df:      pd.DataFrame,
    source_id_col:  str,
    source_cat_col: str,
    crosswalk:      dict,
    usda_df:        pd.DataFrame,
    threshold:      float = 0.20,
    top_n:          int   = 3
) -> pd.DataFrame:
    """
    For every food in source_df, find its top-n USDA matches within the
    mapped category block and return all pairs above the threshold.
 
    threshold=0.20 is permissive — we keep LOW-confidence matches so
    they can be reviewed or used for category-level borrowing.
    Raise to 0.65 if you only want high-confidence direct borrowing.
    """
    all_links = []
    for src_cat, usda_cats in crosswalk.items():
        src_block  = source_df[source_df[source_cat_col] == src_cat].copy()
        usda_block = usda_df[usda_df["usda_category"].isin(usda_cats)].copy()
        if src_block.empty or usda_block.empty:
            continue
 
        q_names  = src_block["name_norm"].tolist()
        c_names  = usda_block["name_norm"].tolist()
        c_ids    = usda_block["fdc_id"].tolist()
        src_ids  = src_block[source_id_col].tolist()
        src_orig = src_block["food_name_normalized"].tolist()
 
        matches = tfidf_cosine_match(q_names, c_names, c_ids, top_n=top_n)
        print(matches)
 
        for qi, usda_fdc_id, score in matches:
            if score < threshold:
                continue
            usda_row = usda_df[usda_df["fdc_id"] == usda_fdc_id].iloc[0]
            all_links.append({
                "source_food_id":   src_ids[qi],
                "source_food_name": src_orig[qi],
                "source_category":  src_cat,
                "usda_fdc_id":      usda_fdc_id,
                "usda_food_name":   usda_row["description"],
                "usda_category":    usda_row["usda_category"],
                "similarity_score": round(score, 4),
            })
    return pd.DataFrame(all_links)
 
print("Matching TKPI → USDA ...")
tkpi_links  = match_to_usda(tkpi,  "food_id", "category_normalized",
                             CROSSWALK_TKPI,  usda, threshold=0.20)
 
print("Matching MyFCD → USDA ...")
myfcd_links = match_to_usda(myfcd, "food_id", "category_normalized",
                             CROSSWALK_MYFCD, usda, threshold=0.20)

Matching TKPI → USDA ...
[(0, 169742, 0.23722194568422636), (0, 168914, 0.23722194568422636), (0, 173900, 0.2332726236390852), (1, 169742, 0.16527453901707134), (1, 168914, 0.16527453901707134), (1, 173900, 0.16252301289431742), (2, 169742, 0.16254601604875105), (2, 168914, 0.16254601604875105), (2, 173900, 0.1598399149640491), (3, 169742, 0.24149824324249203), (3, 168914, 0.24149824324249203), (3, 173900, 0.2374777284745624), (4, 170288, 0.46812433035054746), (4, 170290, 0.41730210597507705), (4, 169695, 0.33897451560173664), (5, 168920, 0.2931423012655934), (5, 169748, 0.2547689799613331), (5, 169694, 0.19431396850432134), (6, 169711, 0.35587445827047953), (6, 168883, 0.297643060127306), (6, 169742, 0.12752198574818474), (7, 169711, 0.471132115911843), (7, 168883, 0.39404121719146673), (7, 169714, 0.22064702578242573), (8, 169742, 0.22447529858970833), (8, 168914, 0.22447529858970833), (8, 173900, 0.2207381854707979), (9, 169742, 0.1825897245714126), (9, 168914, 0.1825897245714126), (9, 173900, 0.17954993151016682), (10, 169707, 0.5811534264509153), (10, 169708, 0.5811534264509153), (10, 169758, 0.5743880441820891), (11, 169742, 0.19673793506852516), (11, 168914, 0.19673793506852516), (11, 173900, 0.19346259955165046), (12, 168898, 0.3724961139974958), (12, 172026, 0.20915632437588838), (12, 168876, 0.20445422872115132), (13, 169716, 0.5498249685107414), (13, 168943, 0.48898576188799464), (13, 173262, 0.3644998423167793), (14, 170288, 0.37365976872216305), (14, 170290, 0.3330931513197657), (14, 169695, 0.2705715787248315), (15, 170288, 0.4438264740257456), (15, 170290, 0.39564216232842486), (15, 169695, 0.3213801426032372), (16, 168920, 0.19241890012241428), (16, 170288, 0.1718608519563272), (16, 169748, 0.16723061358876953), (17, 168920, 0.19241890012241428), (17, 170288, 0.1718608519563272), (17, 169748, 0.16723061358876953), (18, 175084, 0.0), (18, 171682, 0.0), (18, 171842, 0.0), (19, 168871, 0.5228832465473904), (19, 169702, 0.5228832465473904), (19, 174913, 0.5052000276596749), (20, 168871, 0.43089174895027565), (20, 169702, 0.43089174895027565), (20, 172023, 0.3661403010594725), (21, 175084, 0.0), (21, 171682, 0.0), (21, 171842, 0.0), (22, 175084, 0.0), (22, 171682, 0.0), (22, 171842, 0.0), (23, 175084, 0.0), (23, 171682, 0.0), (23, 171842, 0.0), (24, 175084, 0.0), (24, 171682, 0.0), (24, 171842, 0.0), (25, 175084, 0.0), (25, 171682, 0.0), (25, 171842, 0.0), (26, 175084, 0.0), (26, 171682, 0.0), (26, 171842, 0.0), (27, 175084, 0.0), (27, 171682, 0.0), (27, 171842, 0.0), (28, 175084, 0.0), (28, 171682, 0.0), (28, 171842, 0.0), (29, 175084, 0.0), (29, 171682, 0.0), (29, 171842, 0.0), (30, 175084, 0.0), (30, 171682, 0.0), (30, 171842, 0.0), (31, 175084, 0.0), (31, 171682, 0.0), (31, 171842, 0.0), (32, 175084, 0.0), (32, 171682, 0.0), (32, 171842, 0.0), (33, 175084, 0.0), (33, 171682, 0.0), (33, 171842, 0.0), (34, 175084, 0.0), (34, 171682, 0.0), (34, 171842, 0.0), (35, 175084, 0.0), (35, 171682, 0.0), (35, 171842, 0.0), (36, 175084, 0.0), (36, 171682, 0.0), (36, 171842, 0.0), (37, 175084, 0.0), (37, 171682, 0.0), (37, 171842, 0.0), (38, 175084, 0.0), (38, 171682, 0.0), (38, 171842, 0.0), (39, 175084, 0.0), (39, 171682, 0.0), (39, 171842, 0.0), (40, 175084, 0.0), (40, 171682, 0.0), (40, 171842, 0.0), (41, 175084, 0.0), (41, 171682, 0.0), (41, 171842, 0.0), (42, 175084, 0.0), (42, 171682, 0.0), (42, 171842, 0.0), (43, 175084, 0.0), (43, 171682, 0.0), (43, 171842, 0.0), (44, 174075, 0.38561878173310116), (44, 171844, 0.378870509985521), (44, 171668, 0.0), (45, 175084, 0.0), (45, 171682, 0.0), (45, 171842, 0.0), (46, 175084, 0.0), (46, 171682, 0.0), (46, 171842, 0.0), (47, 175084, 0.0), (47, 171682, 0.0), (47, 171842, 0.0), (48, 175084, 0.0), (48, 171682, 0.0), (48, 171842, 0.0), (49, 175084, 0.0), (49, 171682, 0.0), (49, 171842, 0.0), (50, 175084, 0.0), (50, 171682, 0.0), (50, 171842, 0.0), (51, 175084, 0.0), (51, 171682, 0.0), (51, 171842, 0.0), (52, 175084, 0.0), (52, 171682, 0.0), (52, 171842, 0.0), (53, 175084, 0.0), (53, 171682, 0.0), (53, 171842, 0.0), (54, 175084, 0.0), (54, 171682, 0.0), (54, 171842, 0.0), (55, 175084, 0.0), (55, 171682, 0.0), (55, 171842, 0.0), (56, 175084, 0.0), (56, 171682, 0.0), (56, 171842, 0.0), (57, 175084, 0.0), (57, 171682, 0.0), (57, 171842, 0.0), (58, 175084, 0.0), (58, 171682, 0.0), (58, 171842, 0.0), (59, 175084, 0.0), (59, 171682, 0.0), (59, 171842, 0.0), (60, 175084, 0.0), (60, 171682, 0.0), (60, 171842, 0.0), (61, 169723, 0.23844879766003022), (61, 174947, 0.2331756509054187), (61, 175055, 0.2285478466830334), (62, 175084, 0.0), (62, 171682, 0.0), (62, 171842, 0.0), (63, 175084, 0.0), (63, 171682, 0.0), (63, 171842, 0.0), (64, 175084, 0.0), (64, 171682, 0.0), (64, 171842, 0.0), (65, 175084, 0.0), (65, 171682, 0.0), (65, 171842, 0.0), (66, 175084, 0.0), (66, 171682, 0.0), (66, 171842, 0.0), (67, 175084, 0.0), (67, 171682, 0.0), (67, 171842, 0.0), (68, 175084, 0.0), (68, 171682, 0.0), (68, 171842, 0.0), (69, 175084, 0.0), (69, 171682, 0.0), (69, 171842, 0.0), (70, 175084, 0.0), (70, 171682, 0.0), (70, 171842, 0.0), (71, 175084, 0.0), (71, 171682, 0.0), (71, 171842, 0.0), (72, 175084, 0.0), (72, 171682, 0.0), (72, 171842, 0.0), (73, 175084, 0.0), (73, 171682, 0.0), (73, 171842, 0.0), (74, 175084, 0.0), (74, 171682, 0.0), (74, 171842, 0.0), (75, 175084, 0.0), (75, 171682, 0.0), (75, 171842, 0.0), (76, 175084, 0.0), (76, 171682, 0.0), (76, 171842, 0.0), (77, 175084, 0.0), (77, 171682, 0.0), (77, 171842, 0.0), (78, 175084, 0.0), (78, 171682, 0.0), (78, 171842, 0.0), (79, 175084, 0.0), (79, 171682, 0.0), (79, 171842, 0.0), (80, 175084, 0.0), (80, 171682, 0.0), (80, 171842, 0.0), (81, 175084, 0.0), (81, 171682, 0.0), (81, 171842, 0.0), (82, 175084, 0.0), (82, 171682, 0.0), (82, 171842, 0.0), (83, 175084, 0.0), (83, 171682, 0.0), (83, 171842, 0.0), (84, 175084, 0.0), (84, 171682, 0.0), (84, 171842, 0.0), (85, 175084, 0.0), (85, 171682, 0.0), (85, 171842, 0.0), (86, 175084, 0.0), (86, 171682, 0.0), (86, 171842, 0.0), (87, 175084, 0.0), (87, 171682, 0.0), (87, 171842, 0.0), (88, 175084, 0.0), (88, 171682, 0.0), (88, 171842, 0.0), (89, 175084, 0.0), (89, 171682, 0.0), (89, 171842, 0.0), (90, 175084, 0.0), (90, 171682, 0.0), (90, 171842, 0.0), (91, 175084, 0.0), (91, 171682, 0.0), (91, 171842, 0.0), (92, 175084, 0.0), (92, 171682, 0.0), (92, 171842, 0.0), (93, 175084, 0.0), (93, 171682, 0.0), (93, 171842, 0.0), (94, 175084, 0.0), (94, 171682, 0.0), (94, 171842, 0.0), (95, 175084, 0.0), (95, 171682, 0.0), (95, 171842, 0.0), (96, 175084, 0.0), (96, 171682, 0.0), (96, 171842, 0.0), (97, 175084, 0.0), (97, 171682, 0.0), (97, 171842, 0.0), (98, 175084, 0.0), (98, 171682, 0.0), (98, 171842, 0.0), (99, 175084, 0.0), (99, 171682, 0.0), (99, 171842, 0.0), (100, 175084, 0.0), (100, 171682, 0.0), (100, 171842, 0.0), (101, 175084, 0.0), (101, 171682, 0.0), (101, 171842, 0.0), (102, 175084, 0.0), (102, 171682, 0.0), (102, 171842, 0.0), (103, 175084, 0.0), (103, 171682, 0.0), (103, 171842, 0.0), (104, 175084, 0.0), (104, 171682, 0.0), (104, 171842, 0.0), (105, 175084, 0.0), (105, 171682, 0.0), (105, 171842, 0.0), (106, 175084, 0.0), (106, 171682, 0.0), (106, 171842, 0.0), (107, 175084, 0.0), (107, 171682, 0.0), (107, 171842, 0.0), (108, 175084, 0.0), (108, 171682, 0.0), (108, 171842, 0.0), (109, 175084, 0.0), (109, 171682, 0.0), (109, 171842, 0.0), (110, 175084, 0.0), (110, 171682, 0.0), (110, 171842, 0.0), (111, 175084, 0.0), (111, 171682, 0.0), (111, 171842, 0.0), (112, 175084, 0.0), (112, 171682, 0.0), (112, 171842, 0.0), (113, 175084, 0.0), (113, 171682, 0.0), (113, 171842, 0.0), (114, 175084, 0.0), (114, 171682, 0.0), (114, 171842, 0.0), (115, 175084, 0.0), (115, 171682, 0.0), (115, 171842, 0.0), (116, 175084, 0.0), (116, 171682, 0.0), (116, 171842, 0.0), (117, 175084, 0.0), (117, 171682, 0.0), (117, 171842, 0.0), (118, 175084, 0.0), (118, 171682, 0.0), (118, 171842, 0.0), (119, 175084, 0.0), (119, 171682, 0.0), (119, 171842, 0.0), (120, 175084, 0.0), (120, 171682, 0.0), (120, 171842, 0.0), (121, 175084, 0.0), (121, 171682, 0.0), (121, 171842, 0.0), (122, 175084, 0.0), (122, 171682, 0.0), (122, 171842, 0.0), (123, 174075, 0.348391596460344), (123, 171844, 0.3422947949588162), (123, 171668, 0.0), (124, 174075, 0.27703295480580314), (124, 171844, 0.2721849189978414), (124, 171668, 0.0), (125, 175084, 0.0), (125, 171682, 0.0), (125, 171842, 0.0), (126, 168911, 0.7160313647891071), (126, 168912, 0.7160313647891071), (126, 168934, 0.6023379164527133), (127, 175084, 0.0), (127, 171682, 0.0), (127, 171842, 0.0), (128, 175084, 0.0), (128, 171682, 0.0), (128, 171842, 0.0), (129, 175084, 0.0), (129, 171682, 0.0), (129, 171842, 0.0), (130, 175084, 0.0), (130, 171682, 0.0), (130, 171842, 0.0), (131, 175084, 0.0), (131, 171682, 0.0), (131, 171842, 0.0), (132, 175084, 0.0), (132, 171682, 0.0), (132, 171842, 0.0), (133, 175084, 0.0), (133, 171682, 0.0), (133, 171842, 0.0), (134, 175084, 0.0), (134, 171682, 0.0), (134, 171842, 0.0)]

[(0, 169250, 0.6346253567452287), (0, 168536, 0.596793477917662), (0, 168430, 0.5698135597227014), (1, 170551, 0.0), (1, 169237, 0.0), (1, 169247, 0.0), (2, 170551, 0.0), (2, 169237, 0.0), (2, 169247, 0.0), (3, 168412, 0.6864981002085417), (3, 170551, 0.0), (3, 169236, 0.0), (4, 170007, 0.4780232404070812), (4, 170414, 0.23825349522753123), (4, 169397, 0.2315046347081322), (5, 168414, 0.21639128715264905), (5, 168530, 0.20792184262770605), (5, 168415, 0.201541463508756), (6, 170414, 0.23825349522753123), (6, 169397, 0.2315046347081322), (6, 170415, 0.20355519970676617), (7, 168462, 0.6364365181085462), (7, 170531, 0.5420556683222161), (7, 168463, 0.48872952350543875), (8, 168462, 0.4610745963152), (8, 170531, 0.3926991794795247), (8, 168463, 0.3540663700871383), (9, 170375, 0.5289089006244768), (9, 168508, 0.493353511048047), (9, 170376, 0.4685053294214235), (10, 170402, 0.27609496482938856), (10, 169344, 0.2605956997812643), (10, 170403, 0.24943942792447815), (11, 170402, 0.36839158998786553), (11, 169344, 0.3477110285069628), (11, 170403, 0.3328252926146114), (12, 169222, 0.32329115925435326), (12, 169359, 0.30327550222036687), (12, 170478, 0.29345984447750717), (13, 168459, 0.3113926824582679), (13, 169368, 0.30351232796719546), (13, 169281, 0.28999630573887714), (14, 168553, 0.3219848329750851), (14, 170464, 0.307034770384353), (14, 170551, 0.0), (15, 170551, 0.0), (15, 169237, 0.0), (15, 169247, 0.0), (16, 170551, 0.0), (16, 169237, 0.0), (16, 169247, 0.0), (17, 169249, 0.15980102171941432), (17, 168431, 0.15499096168487142), (17, 170124, 0.15080618000172255), (18, 170551, 0.0), (18, 169237, 0.0), (18, 169247, 0.0), (19, 170551, 0.0), (19, 169237, 0.0), (19, 169247, 0.0), (20, 170551, 0.0), (20, 169237, 0.0), (20, 169247, 0.0), (21, 169249, 0.13194505652211233), (21, 168431, 0.127973469630466), (21, 170124, 0.12451816471579975), (22, 170551, 0.0), (22, 169237, 0.0), (22, 169247, 0.0), (23, 170551, 0.0), (23, 169237, 0.0), (23, 169247, 0.0), (24, 169274, 0.5720249354291738), (24, 170121, 0.515548818537917), (24, 169275, 0.47923043662698944), (25, 170551, 0.0), (25, 169237, 0.0), (25, 169247, 0.0), (26, 170551, 0.0), (26, 169237, 0.0), (26, 169247, 0.0), (27, 168405, 0.22202088467427825), (27, 168528, 0.21182945622833835), (27, 169221, 0.2042900934778432), (28, 170551, 0.0), (28, 169237, 0.0), (28, 169247, 0.0), (29, 170551, 0.0), (29, 169237, 0.0), (29, 169247, 0.0), (30, 170551, 0.0), (30, 169237, 0.0), (30, 169247, 0.0), (31, 170551, 0.0), (31, 169237, 0.0), (31, 169247, 0.0), (32, 169222, 0.20736895536513617), (32, 169359, 0.1945302934615515), (32, 170478, 0.1882342267919489), (33, 168553, 0.24873814278723175), (33, 170464, 0.23718899381331313), (33, 170551, 0.0), (34, 169249, 0.13354207076644486), (34, 168431, 0.12952241325354338), (34, 170124, 0.12602528660403778), (35, 170478, 0.5602767895514333), (35, 170550, 0.5411638425996506), (35, 170070, 0.4810370015747784), (36, 169249, 0.1759541909394993), (36, 168431, 0.1706579155299811), (36, 170124, 0.1660501234933959), (37, 168416, 0.37636229420989453), (37, 168553, 0.3559088938055533), (37, 170483, 0.3536332002863029), (38, 169249, 0.13194505652211233), (38, 168431, 0.127973469630466), (38, 170124, 0.12451816471579975), (39, 169249, 0.1759541909394993), (39, 168431, 0.1706579155299811), (39, 170124, 0.1660501234933959), (40, 169230, 0.6018309513381622), (40, 169249, 0.17979607458571426), (40, 168431, 0.17438415729365248), (41, 169256, 0.29741238584293106), (41, 169891, 0.29630788477508685), (41, 170503, 0.272897299190614), (42, 170551, 0.0), (42, 169237, 0.0), (42, 169247, 0.0), (43, 169975, 0.5036324315573458), (43, 169976, 0.3793049728259818), (43, 169977, 0.36430955876622095), (44, 169249, 0.1759541909394993), (44, 168431, 0.1706579155299811), (44, 170124, 0.1660501234933959), (45, 170402, 0.3760232460443491), (45, 169344, 0.35491426291494343), (45, 170403, 0.339720151859951), (46, 170551, 0.0), (46, 169237, 0.0), (46, 169247, 0.0), (47, 169249, 0.17979607458571426), (47, 168431, 0.17438415729365248), (47, 170124, 0.16967575611115265), (48, 170551, 0.0), (48, 169237, 0.0), (48, 169247, 0.0), (49, 170551, 0.0), (49, 169237, 0.0), (49, 169247, 0.0), (50, 170095, 0.5104662415733775), (50, 169249, 0.18390113017944293), (50, 168431, 0.17836564944805822), (51, 169308, 0.4275031454130149), (51, 170543, 0.398916359154868), (51, 168486, 0.3572676790899431), (52, 170551, 0.0), (52, 169237, 0.0), (52, 169247, 0.0), (53, 170551, 0.0), (53, 169237, 0.0), (53, 169247, 0.0), (54, 170085, 0.24733444670813903), (54, 169249, 0.1490736015360817), (54, 168431, 0.14458644015726957), (55, 169249, 0.17979607458571426), (55, 168431, 0.17438415729365248), (55, 170124, 0.16967575611115265), (56, 170551, 0.0), (56, 169237, 0.0), (56, 169247, 0.0), (57, 169249, 0.15660784134904357), (57, 168431, 0.15189389702838876), (57, 170124, 0.14779273660486097), (58, 168553, 0.3958544467971684), (58, 170464, 0.37747454765174737), (58, 169249, 0.19857683984292077), (59, 168553, 0.2805192607039574), (59, 170464, 0.2674944841432721), (59, 169249, 0.14071997613356793), (60, 168553, 0.22920918587469102), (60, 170464, 0.21856678497793036), (60, 169249, 0.11498073638487254), (61, 168553, 0.2561160284857088), (61, 170464, 0.24422431724896443), (61, 169249, 0.12847831313076288), (62, 169249, 0.14928717430365546), (62, 168431, 0.14479358431867595), (62, 170124, 0.14088413351646564), (63, 168393, 0.20408551748434703), (63, 168496, 0.19846081390630566), (63, 168394, 0.1940889285243474), (64, 169249, 0.19231267493677398), (64, 168431, 0.1865240041141704), (64, 170124, 0.18148782505315125), (65, 169249, 0.1759541909394993), (65, 168431, 0.1706579155299811), (65, 170124, 0.1660501234933959), (66, 169249, 0.14928717430365546), (66, 168431, 0.14479358431867595), (66, 170124, 0.14088413351646564), (67, 170551, 0.0), (67, 169237, 0.0), (67, 169247, 0.0), (68, 170551, 0.0), (68, 169237, 0.0), (68, 169247, 0.0), (69, 170551, 0.0), (69, 169237, 0.0), (69, 169247, 0.0), (70, 169249, 0.19857683984292077), (70, 168431, 0.19259961572484607), (70, 170124, 0.18739939414221218), (71, 169249, 0.11937184342274301), (71, 168431, 0.11577871412282133), (71, 170124, 0.11265266963033783), (72, 169249, 0.11498073638487254), (72, 168431, 0.11151978076095742), (72, 170124, 0.10850872817592926), (73, 169249, 0.11498073638487254), (73, 168431, 0.11151978076095742), (73, 170124, 0.10850872817592926), (74, 170551, 0.0), (74, 169237, 0.0), (74, 169247, 0.0), (75, 169308, 0.5303748500239654), (75, 170543, 0.49490911687787614), (75, 168486, 0.4432383568375264), (76, 169301, 0.30031854808557745), (76, 170132, 0.2832796431097288), (76, 169302, 0.2710347260940464), (77, 170542, 0.3940263385121784), (77, 169307, 0.3590660620365619), (77, 169303, 0.3216248834070585), (78, 170542, 0.3560209207037921), (78, 169307, 0.32443270285544795), (78, 169303, 0.2906028757980901), (79, 170542, 0.39932127470735096), (79, 169307, 0.3638912011262848), (79, 169303, 0.32594688696359886), (80, 170542, 0.3847273573182064), (80, 169307, 0.35059213978334597), (80, 169303, 0.3140345691310924), (81, 170551, 0.0), (81, 169237, 0.0), (81, 169247, 0.0), (82, 170551, 0.0), (82, 169237, 0.0), (82, 169247, 0.0), (83, 169249, 0.3550121470972142), (83, 168431, 0.3443261719879442), (83, 169247, 0.24652881232693483), (84, 168568, 0.32287305641035746), (84, 168565, 0.2715526905920574), (84, 169318, 0.2413986748588507), (85, 170551, 0.0), (85, 169237, 0.0), (85, 169247, 0.0), (86, 170551, 0.0), (86, 169237, 0.0), (86, 169247, 0.0), (87, 170551, 0.0), (87, 169237, 0.0), (87, 169247, 0.0), (88, 168582, 0.3728779753107976), (88, 169376, 0.23732212413422016), (88, 169237, 0.0), (89, 168580, 0.4026573017630399), (89, 169277, 0.2924616596680007), (89, 169376, 0.2399269703238452), (90, 170551, 0.0), (90, 169237, 0.0), (90, 169247, 0.0), (91, 169394, 0.3442010479794016), (91, 168459, 0.2863899952437875), (91, 169368, 0.279142378930517), (92, 170551, 0.0), (92, 169237, 0.0), (92, 169247, 0.0), (93, 170551, 0.0), (93, 169237, 0.0), (93, 169247, 0.0), (94, 170551, 0.0), (94, 169237, 0.0), (94, 169247, 0.0), (95, 169222, 0.21386388730264635), (95, 169359, 0.2006231100723694), (95, 170478, 0.19412984645773182), (96, 169222, 0.22361539948907022), (96, 169359, 0.20977088498389726), (96, 170478, 0.20298154922699008), (97, 170551, 0.0), (97, 169237, 0.0), (97, 169247, 0.0), (98, 170551, 0.0), (98, 169237, 0.0), (98, 169247, 0.0), (99, 170551, 0.0), (99, 169237, 0.0), (99, 169247, 0.0), (100, 170551, 0.0), (100, 169237, 0.0), (100, 169247, 0.0), (101, 170551, 0.0), (101, 169237, 0.0), (101, 169247, 0.0), (102, 170551, 0.0), (102, 169237, 0.0), (102, 169247, 0.0), (103, 170478, 0.5540271070756608), (103, 170550, 0.5351273580500683), (103, 170070, 0.47567120992499945), (104, 169231, 0.3857186150586669), (104, 169977, 0.2399815304797895), (104, 169765, 0.22599968290933925), (105, 170551, 0.0), (105, 169237, 0.0), (105, 169247, 0.0), (106, 170551, 0.0), (106, 169237, 0.0), (106, 169247, 0.0), (107, 170551, 0.0), (107, 169237, 0.0), (107, 169247, 0.0), (108, 168409, 0.3989874182739565), (108, 169225, 0.38490884969454964), (108, 169379, 0.33149172301680074), (109, 168409, 0.20235304252138187), (109, 169225, 0.1952128645209999), (109, 169379, 0.16812148867573273), (110, 168409, 0.20235304252138187), (110, 169225, 0.1952128645209999), (110, 169379, 0.16812148867573273), (111, 169234, 0.4138412198221753), (111, 168533, 0.38966466350875867), (111, 169235, 0.37236816407820167), (112, 169986, 0.3688783212829292), (112, 168520, 0.3221580303586795), (112, 168521, 0.3221580303586795), (113, 169975, 0.2814494036021571), (113, 169976, 0.21197038096830617), (113, 169977, 0.20359035998586766), (114, 169234, 0.280570791162378), (114, 168533, 0.26417987791465514), (114, 169235, 0.2524534178688041), (115, 170551, 0.0), (115, 169237, 0.0), (115, 169247, 0.0), (116, 169994, 0.6072624116297408), (116, 170075, 0.4428623169259695), (116, 169392, 0.34068152877208746), (117, 170551, 0.0), (117, 169237, 0.0), (117, 169247, 0.0), (118, 168409, 0.33337858930533626), (118, 170085, 0.211371868289291), (118, 170551, 0.0), (119, 168414, 0.21639128715264905), (119, 168530, 0.20792184262770605), (119, 168415, 0.201541463508756), (120, 168414, 0.19299994358115888), (120, 168530, 0.1854460243037868), (120, 168415, 0.1797553478158971), (121, 168448, 0.5076727135757688), (121, 170527, 0.4737250537566509), (121, 170526, 0.4388685404576641), (122, 170402, 0.39600433061709966), (122, 169344, 0.37377366051331035), (122, 170403, 0.35777216634785525), (123, 168448, 0.5076727135757688), (123, 170527, 0.4737250537566509), (123, 170526, 0.4388685404576641), (124, 170551, 0.0), (124, 169237, 0.0), (124, 169247, 0.0), (125, 170061, 0.4659057834893956), (125, 170140, 0.4285131238236375), (125, 170139, 0.4285131238236375), (126, 170551, 0.0), (126, 169237, 0.0), (126, 169247, 0.0), (127, 170085, 0.26972154668089726), (127, 170551, 0.0), (127, 169236, 0.0), (128, 169256, 0.268290432480633), (128, 169891, 0.2672940816786064), (128, 170503, 0.24617580809601217), (129, 168405, 0.26992959342606154), (129, 168528, 0.2575390107073266), (129, 169221, 0.24837276886967968), (130, 168393, 0.20271662509421964), (130, 168496, 0.19712964890624304), (130, 168394, 0.19278708770516562), (131, 168414, 0.17870017964264465), (131, 168530, 0.17170594582669133), (131, 168415, 0.16643690329846678), (132, 170551, 0.0), (132, 169237, 0.0), (132, 169247, 0.0), (133, 169222, 0.2658081462460328), (133, 169359, 0.24935138725401082), (133, 170478, 0.2412810094718509), (134, 170416, 0.6707939708034711), (134, 170486, 0.48919440163064976), (134, 170551, 0.0), (135, 170551, 0.0), (135, 169237, 0.0), (135, 169247, 0.0), (136, 170551, 0.0), (136, 169237, 0.0), (136, 169247, 0.0), (137, 169210, 0.39838835756037344), (137, 168497, 0.37392297255607315), (137, 169211, 0.3565587692126011), (138, 170551, 0.0), (138, 169237, 0.0), (138, 169247, 0.0), (139, 170495, 0.2930812882696596), (139, 169280, 0.2930812882696596), (139, 170090, 0.2930812882696596), (140, 169256, 0.4109567907149572), (140, 169891, 0.40943061952710963), (140, 169404, 0.38744748859985717), (141, 170390, 0.4908753566297067), (141, 168517, 0.47417243933294534), (141, 170391, 0.4614148585015354), (142, 170551, 0.0), (142, 169237, 0.0), (142, 169247, 0.0), (143, 170551, 0.0), (143, 169237, 0.0), (143, 169247, 0.0), (144, 169249, 0.47665612001511004), (144, 168431, 0.4623086238074158), (144, 169247, 0.3310012576091149), (145, 170068, 0.5938568211980995), (145, 170551, 0.0), (145, 169235, 0.0), (146, 169988, 0.6470228908168814), (146, 169342, 0.5798804352326363), (146, 169989, 0.5372702954319988), (147, 169957, 0.35106785626423187), (147, 168499, 0.330458752828322), (147, 169137, 0.3157256619731561), (148, 169222, 0.19348410205849492), (148, 169359, 0.18150508154564277), (148, 170478, 0.17563058213504637), (149, 170551, 0.0), (149, 169237, 0.0), (149, 169247, 0.0), (150, 170551, 0.0), (150, 169237, 0.0), (150, 169247, 0.0), (151, 170551, 0.0), (151, 169237, 0.0), (151, 169247, 0.0), (152, 170551, 0.0), (152, 169237, 0.0), (152, 169247, 0.0), (153, 169228, 0.6749463546064973), (153, 169352, 0.6018339926566733), (153, 169229, 0.5559854715449872), (154, 170551, 0.0), (154, 169237, 0.0), (154, 169247, 0.0), (155, 170551, 0.0), (155, 169237, 0.0), (155, 169247, 0.0), (156, 170551, 0.0), (156, 169237, 0.0), (156, 169247, 0.0), (157, 170551, 0.0), (157, 169237, 0.0), (157, 169247, 0.0), (158, 169228, 0.5706140102721438), (158, 169352, 0.5088032637321757), (158, 169229, 0.47004194838017427), (159, 170458, 0.4572929843165654), (159, 170545, 0.4350832611720115), (159, 167708, 0.3053536402229819), (160, 170463, 0.3249805453789506), (160, 170051, 0.30087208574590785), (160, 170054, 0.2940443193243822), (161, 170463, 0.33273237011303725), (161, 170462, 0.302582176633214), (161, 170054, 0.3010582161864189), (162, 168459, 0.23146833514568652), (162, 169368, 0.2256106106802093), (162, 169281, 0.21556371061087254), (163, 170551, 0.0), (163, 169237, 0.0), (163, 169247, 0.0), (164, 168405, 0.2386277517969338), (164, 168528, 0.22767401804696777), (164, 169221, 0.2195707209820469), (165, 170491, 0.5398755125100321), (165, 170500, 0.5360179976079543), (165, 169235, 0.0), (166, 170551, 0.0), (166, 169237, 0.0), (166, 169247, 0.0), (167, 170551, 0.0), (167, 169237, 0.0), (167, 169247, 0.0), (168, 170551, 0.0), (168, 169237, 0.0), (168, 169247, 0.0), (169, 170551, 0.0), (169, 169237, 0.0), (169, 169247, 0.0), (170, 170551, 0.0), (170, 169237, 0.0), (170, 169247, 0.0), (171, 170551, 0.0), (171, 169237, 0.0), (171, 169247, 0.0), (172, 170551, 0.0), (172, 169237, 0.0), (172, 169247, 0.0), (173, 170551, 0.0), (173, 169237, 0.0), (173, 169247, 0.0), (174, 170551, 0.0), (174, 169237, 0.0), (174, 169247, 0.0), (175, 170551, 0.0), (175, 169237, 0.0), (175, 169247, 0.0), (176, 170551, 0.0), (176, 169237, 0.0), (176, 169247, 0.0), (177, 170551, 0.0), (177, 169237, 0.0), (177, 169247, 0.0), (178, 170551, 0.0), (178, 169237, 0.0), (178, 169247, 0.0), (179, 170551, 0.0), (179, 169237, 0.0), (179, 169247, 0.0), (180, 170551, 0.0), (180, 169237, 0.0), (180, 169247, 0.0), (181, 170551, 0.0), (181, 169237, 0.0), (181, 169247, 0.0), (182, 170551, 0.0), (182, 169237, 0.0), (182, 169247, 0.0), (183, 170551, 0.0), (183, 169237, 0.0), (183, 169247, 0.0), (184, 170551, 0.0), (184, 169237, 0.0), (184, 169247, 0.0), (185, 170551, 0.0), (185, 169237, 0.0), (185, 169247, 0.0), (186, 170551, 0.0), (186, 169237, 0.0), (186, 169247, 0.0), (187, 170551, 0.0), (187, 169237, 0.0), (187, 169247, 0.0), (188, 170551, 0.0), (188, 169237, 0.0), (188, 169247, 0.0), (189, 170551, 0.0), (189, 169237, 0.0), (189, 169247, 0.0), (190, 170551, 0.0), (190, 169237, 0.0), (190, 169247, 0.0), (191, 170551, 0.0), (191, 169237, 0.0), (191, 169247, 0.0), (192, 170551, 0.0), (192, 169237, 0.0), (192, 169247, 0.0), (193, 170551, 0.0), (193, 169237, 0.0), (193, 169247, 0.0), (194, 170551, 0.0), (194, 169237, 0.0), (194, 169247, 0.0), (195, 170551, 0.0), (195, 169237, 0.0), (195, 169247, 0.0), (196, 170551, 0.0), (196, 169237, 0.0), (196, 169247, 0.0), (197, 170551, 0.0), (197, 169237, 0.0), (197, 169247, 0.0), (198, 170551, 0.0), (198, 169237, 0.0), (198, 169247, 0.0), (199, 170551, 0.0), (199, 169237, 0.0), (199, 169247, 0.0), (200, 170551, 0.0), (200, 169237, 0.0), (200, 169247, 0.0), (201, 170551, 0.0), (201, 169237, 0.0), (201, 169247, 0.0), (202, 170551, 0.0), (202, 169237, 0.0), (202, 169247, 0.0), (203, 170551, 0.0), (203, 169237, 0.0), (203, 169247, 0.0), (204, 170551, 0.0), (204, 169237, 0.0), (204, 169247, 0.0), (205, 170551, 0.0), (205, 169237, 0.0), (205, 169247, 0.0), (206, 170551, 0.0), (206, 169237, 0.0), (206, 169247, 0.0), (207, 170551, 0.0), (207, 169237, 0.0), (207, 169247, 0.0), (208, 170551, 0.0), (208, 169237, 0.0), (208, 169247, 0.0), (209, 170551, 0.0), (209, 169237, 0.0), (209, 169247, 0.0), (210, 170551, 0.0), (210, 169237, 0.0), (210, 169247, 0.0), (211, 170551, 0.0), (211, 169237, 0.0), (211, 169247, 0.0), (212, 170551, 0.0), (212, 169237, 0.0), (212, 169247, 0.0), (213, 170551, 0.0), (213, 169237, 0.0), (213, 169247, 0.0), (214, 170551, 0.0), (214, 169237, 0.0), (214, 169247, 0.0), (215, 170551, 0.0), (215, 169237, 0.0), (215, 169247, 0.0), (216, 170551, 0.0), (216, 169237, 0.0), (216, 169247, 0.0), (217, 170551, 0.0), (217, 169237, 0.0), (217, 169247, 0.0), (218, 170551, 0.0), (218, 169237, 0.0), (218, 169247, 0.0), (219, 170551, 0.0), (219, 169237, 0.0), (219, 169247, 0.0), (220, 170551, 0.0), (220, 169237, 0.0), (220, 169247, 0.0), (221, 170551, 0.0), (221, 169237, 0.0), (221, 169247, 0.0), (222, 170551, 0.0), (222, 169237, 0.0), (222, 169247, 0.0), (223, 170551, 0.0), (223, 169237, 0.0), (223, 169247, 0.0), (224, 170551, 0.0), (224, 169237, 0.0), (224, 169247, 0.0), (225, 170551, 0.0), (225, 169237, 0.0), (225, 169247, 0.0), (226, 170551, 0.0), (226, 169237, 0.0), (226, 169247, 0.0)]

[(0, 174687, 0.0), (0, 168173, 0.0), (0, 168197, 0.0), (1, 174687, 0.0), (1, 168173, 0.0), (1, 168197, 0.0), (2, 168215, 0.2210992057893364), (2, 168216, 0.2210992057893364), (2, 168199, 0.2210992057893364), (3, 174687, 0.0), (3, 168173, 0.0), (3, 168197, 0.0), (4, 174687, 0.0), (4, 168173, 0.0), (4, 168197, 0.0), (5, 171715, 0.46778312065910127), (5, 174687, 0.0), (5, 168205, 0.0), (6, 174687, 0.0), (6, 168173, 0.0), (6, 168197, 0.0), (7, 174687, 0.0), (7, 168173, 0.0), (7, 168197, 0.0), (8, 174687, 0.0), (8, 168173, 0.0), (8, 168197, 0.0), (9, 174687, 0.0), (9, 168173, 0.0), (9, 168197, 0.0), (10, 169942, 0.6103313308015046), (10, 169941, 0.6103313308015046), (10, 169943, 0.265596514635734), (11, 174687, 0.0), (11, 168173, 0.0), (11, 168197, 0.0), (12, 174687, 0.0), (12, 168173, 0.0), (12, 168197, 0.0), (13, 169108, 0.6301854497595362), (13, 169109, 0.41569342247878754), (13, 169110, 0.40775032327898453), (14, 174687, 0.0), (14, 168173, 0.0), (14, 168197, 0.0), (15, 174687, 0.0), (15, 168173, 0.0), (15, 168197, 0.0), (16, 174687, 0.0), (16, 168173, 0.0), (16, 168197, 0.0), (17, 174687, 0.0), (17, 168173, 0.0), (17, 168197, 0.0), (18, 174687, 0.0), (18, 168173, 0.0), (18, 168197, 0.0), (19, 169107, 0.6459345529170545), (19, 169927, 0.5496513994147417), (19, 167764, 0.3183551641195616), (20, 174687, 0.0), (20, 168173, 0.0), (20, 168197, 0.0), (21, 174687, 0.0), (21, 168173, 0.0), (21, 168197, 0.0), (22, 168192, 1.0), (22, 174687, 0.0), (22, 168196, 0.0), (23, 168150, 0.3861122693671011), (23, 168216, 0.0), (23, 168196, 0.0), (24, 174687, 0.0), (24, 168173, 0.0), (24, 168197, 0.0), (25, 174687, 0.0), (25, 168173, 0.0), (25, 168197, 0.0), (26, 169108, 0.6857428569123907), (26, 169109, 0.4523411247261657), (26, 169110, 0.44369775865021155), (27, 174687, 0.0), (27, 168173, 0.0), (27, 168197, 0.0), (28, 174687, 0.0), (28, 168173, 0.0), (28, 168197, 0.0), (29, 174687, 0.0), (29, 168173, 0.0), (29, 168197, 0.0), (30, 174686, 0.3611281944547895), (30, 168210, 0.29692926922899304), (30, 167784, 0.28467692576248715), (31, 174686, 0.23090810744301005), (31, 173039, 0.20134235901668998), (31, 168210, 0.18985882757123357), (32, 169909, 0.16614777030379665), (32, 167771, 0.16343380939101784), (32, 173933, 0.15140540168238628), (33, 169909, 0.16614777030379665), (33, 167771, 0.16343380939101784), (33, 173933, 0.15140540168238628), (34, 167754, 0.6271287906929708), (34, 174687, 0.0), (34, 168206, 0.0), (35, 169099, 0.20687078935337527), (35, 169103, 0.18316374520341533), (35, 167792, 0.15439898129664922), (36, 169105, 0.2687291660938931), (36, 169106, 0.2449284244919608), (36, 169924, 0.22430000890015925), (37, 174687, 0.0), (37, 168173, 0.0), (37, 168197, 0.0), (38, 169099, 0.3238706343652702), (38, 169103, 0.2867556049704847), (38, 167792, 0.2417223629019879), (39, 168156, 0.49857116674281476), (39, 168157, 0.3758005237963572), (39, 174687, 0.0), (40, 174687, 0.0), (40, 168173, 0.0), (40, 168197, 0.0), (41, 169909, 0.18810323583143945), (41, 167771, 0.18503064070313713), (41, 173933, 0.17141274858363195), (42, 174687, 0.0), (42, 168173, 0.0), (42, 168197, 0.0), (43, 174687, 0.0), (43, 168173, 0.0), (43, 168197, 0.0), (44, 174687, 0.0), (44, 168173, 0.0), (44, 168197, 0.0), (45, 174687, 0.0), (45, 168173, 0.0), (45, 168197, 0.0), (46, 174687, 0.0), (46, 168173, 0.0), (46, 168197, 0.0), (47, 169942, 0.4516450897529902), (47, 169941, 0.4516450897529902), (47, 169943, 0.42376286332361346), (48, 174687, 0.0), (48, 168173, 0.0), (48, 168197, 0.0), (49, 171719, 0.3504833561502772), (49, 173958, 0.26013098947760627), (49, 173957, 0.2466907817116373), (50, 174687, 0.0), (50, 168173, 0.0), (50, 168197, 0.0), (51, 167747, 0.8791500210052017), (51, 167802, 0.7077474957535536), (51, 167749, 0.6847632635588414), (52, 174687, 0.0), (52, 168173, 0.0), (52, 168197, 0.0), (53, 169091, 0.49411694355054997), (53, 167785, 0.47871987812019506), (53, 167795, 0.24471527434229928), (54, 169091, 0.2239197274598153), (54, 167785, 0.21694221588113513), (54, 167795, 0.11089799338236152), (55, 169091, 0.2239197274598153), (55, 167785, 0.21694221588113513), (55, 167795, 0.11089799338236152), (56, 169091, 0.2239197274598153), (56, 167785, 0.21694221588113513), (56, 167795, 0.11089799338236152), (57, 169091, 0.2239197274598153), (57, 167785, 0.21694221588113513), (57, 167795, 0.11089799338236152), (58, 169091, 0.2239197274598153), (58, 167785, 0.21694221588113513), (58, 167795, 0.11089799338236152), (59, 169091, 0.2239197274598153), (59, 167785, 0.21694221588113513), (59, 167795, 0.11089799338236152), (60, 169091, 0.2239197274598153), (60, 167785, 0.21694221588113513), (60, 167795, 0.11089799338236152), (61, 169091, 0.2239197274598153), (61, 167785, 0.21694221588113513), (61, 167795, 0.11089799338236152), (62, 169091, 0.298557622109894), (62, 167785, 0.28925433611179513), (62, 167795, 0.14786299347804646), (63, 169090, 0.5580579561080208), (63, 174687, 0.0), (63, 168205, 0.0), (64, 169108, 0.28963873247712957), (64, 168195, 0.0), (64, 168196, 0.0), (65, 174687, 0.0), (65, 168173, 0.0), (65, 168197, 0.0), (66, 169912, 0.6515122489329715), (66, 167791, 0.5190497665153869), (66, 168216, 0.0), (67, 174687, 0.0), (67, 168173, 0.0), (67, 168197, 0.0), (68, 169126, 0.13867172320861237), (68, 167767, 0.13631426050162188), (68, 169125, 0.1278364687248952), (69, 169126, 0.2947284991114607), (69, 167767, 0.28971802235912886), (69, 169125, 0.2716995915765585), (70, 167781, 0.15389008704373638), (70, 169109, 0.13110235845763063), (70, 169110, 0.12859724535685685), (71, 174687, 0.0), (71, 168173, 0.0), (71, 168197, 0.0), (72, 169107, 0.481742070979754), (72, 169927, 0.4099334867211845), (72, 167764, 0.23743129296529666), (73, 173945, 0.16712877772828624), (73, 168213, 0.1566065465485725), (73, 168214, 0.14657195230675937), (74, 173945, 0.08403086362355056), (74, 168213, 0.07874037933175795), (74, 168214, 0.07369507455712278), (75, 173945, 0.10084010355242207), (75, 168213, 0.09449132929470622), (75, 168214, 0.08843677940685819), (76, 173945, 0.10084010355242207), (76, 168213, 0.09449132929470622), (76, 168214, 0.08843677940685819), (77, 173945, 0.10084010355242207), (77, 168213, 0.09449132929470622), (77, 168214, 0.08843677940685819), (78, 173945, 0.10084010355242207), (78, 168213, 0.09449132929470622), (78, 168214, 0.08843677940685819), (79, 173945, 0.10084010355242207), (79, 168213, 0.09449132929470622), (79, 168214, 0.08843677940685819), (80, 173945, 0.10084010355242207), (80, 168213, 0.09449132929470622), (80, 168214, 0.08843677940685819), (81, 173945, 0.10084010355242207), (81, 168213, 0.09449132929470622), (81, 168214, 0.08843677940685819), (82, 173945, 0.10084010355242207), (82, 168213, 0.09449132929470622), (82, 168214, 0.08843677940685819), (83, 173945, 0.1359269292891633), (83, 168213, 0.12736912977091128), (83, 168214, 0.11920792856731073), (84, 173945, 0.06646567454637718), (84, 168213, 0.0622810738893341), (84, 168214, 0.0582904022399212), (85, 173945, 0.07812897693233319), (85, 168213, 0.07321006848167087), (85, 168214, 0.06851911942609568), (86, 173945, 0.11078495345598106), (86, 168213, 0.10381006315077683), (86, 168214, 0.09715841361956164), (87, 173945, 0.0763310957576536), (87, 168213, 0.0715253797901218), (87, 168214, 0.06694237748272563), (88, 173945, 0.10645200033457354), (88, 168213, 0.09974990765916131), (88, 168214, 0.09335841336292791), (89, 173945, 0.10645200033457354), (89, 168213, 0.09974990765916131), (89, 168214, 0.09335841336292791), (90, 173945, 0.10084010355242207), (90, 168213, 0.09449132929470622), (90, 168214, 0.08843677940685819), (91, 173945, 0.13286446140070482), (91, 168213, 0.12449947125700107), (91, 168214, 0.11652214396821622), (92, 173945, 0.2585898008673308), (92, 168213, 0.2423092912960478), (92, 168214, 0.22678327739200577), (93, 173945, 0.10084010355242207), (93, 168213, 0.09449132929470622), (93, 168214, 0.08843677940685819), (94, 168156, 0.3252624613956785), (94, 168157, 0.24516821572805078), (94, 168180, 0.22005033474360464), (95, 168167, 0.7001670011423009), (95, 174687, 0.0), (95, 168205, 0.0), (96, 168167, 0.8024088577726841), (96, 174687, 0.0), (96, 168205, 0.0), (97, 167781, 0.12873782364179046), (97, 169109, 0.10967459065342186), (97, 169110, 0.10757892084930709), (98, 167781, 0.11649942494814831), (98, 169109, 0.09924842894733829), (98, 169110, 0.09735198297556318), (99, 167781, 0.11649942494814831), (99, 169109, 0.09924842894733829), (99, 169110, 0.09735198297556318), (100, 167781, 0.2092172520779647), (100, 169109, 0.17823679032457992), (100, 169110, 0.17483102917935786), (101, 167759, 0.5393537910768672), (101, 174687, 0.0), (101, 168205, 0.0), (102, 167759, 0.5393537910768672), (102, 174687, 0.0), (102, 168205, 0.0), (103, 167759, 0.3650207626091681), (103, 174687, 0.0), (103, 168205, 0.0), (104, 169912, 0.38292234330063635), (104, 167791, 0.3050683286603387), (104, 169125, 0.232167628906266), (105, 167761, 0.683946723553159), (105, 174687, 0.0), (105, 168205, 0.0), (106, 174687, 0.0), (106, 168173, 0.0), (106, 168197, 0.0), (107, 168169, 0.31014884410369015), (107, 168175, 0.25492468439522553), (107, 171693, 0.24426487483930268), (108, 171714, 0.49376024458111306), (108, 174687, 0.0), (108, 168205, 0.0), (109, 171714, 0.5544023648342574), (109, 174687, 0.0), (109, 168205, 0.0), (110, 174687, 0.0), (110, 168173, 0.0), (110, 168197, 0.0), (111, 174687, 0.0), (111, 168173, 0.0), (111, 168197, 0.0), (112, 174687, 0.0), (112, 168173, 0.0), (112, 168197, 0.0), (113, 174687, 0.0), (113, 168173, 0.0), (113, 168197, 0.0), (114, 174687, 0.0), (114, 168173, 0.0), (114, 168197, 0.0), (115, 174687, 0.0), (115, 168173, 0.0), (115, 168197, 0.0), (116, 174687, 0.0), (116, 168173, 0.0), (116, 168197, 0.0), (117, 168192, 0.6661498145005614), (117, 174687, 0.0), (117, 168196, 0.0), (118, 174687, 0.0), (118, 168173, 0.0), (118, 168197, 0.0), (119, 174687, 0.0), (119, 168173, 0.0), (119, 168197, 0.0), (120, 174687, 0.0), (120, 168173, 0.0), (120, 168197, 0.0), (121, 174687, 0.0), (121, 168173, 0.0), (121, 168197, 0.0), (122, 174687, 0.0), (122, 168173, 0.0), (122, 168197, 0.0), (123, 174687, 0.0), (123, 168173, 0.0), (123, 168197, 0.0), (124, 174687, 0.0), (124, 168173, 0.0), (124, 168197, 0.0), (125, 174687, 0.0), (125, 168173, 0.0), (125, 168197, 0.0), (126, 174687, 0.0), (126, 168173, 0.0), (126, 168197, 0.0), (127, 174687, 0.0), (127, 168173, 0.0), (127, 168197, 0.0)]
[(0, 173823, 0.21403535036323335), (0, 173825, 0.21403535036323335), (0, 175275, 0.2020855875749253), (1, 173823, 0.21403535036323335), (1, 173825, 0.21403535036323335), (1, 175275, 0.2020855875749253), (2, 173823, 0.20583229082529078), (2, 173825, 0.20583229082529078), (2, 175274, 0.2003732127125875), (3, 172413, 0.43916342389787905), (3, 172414, 0.43916342389787905), (3, 172415, 0.42009774862588406), (4, 171068, 0.29631690387766596), (4, 171069, 0.29631690387766596), (4, 171067, 0.29631690387766596), (5, 171618, 0.3365118292138026), (5, 171116, 0.11301616739634668), (5, 171513, 0.09532733356973705), (6, 171060, 0.3836940627816329), (6, 172928, 0.36936718982085276), (6, 174491, 0.3445965395138463), (7, 167813, 0.20659417260810503), (7, 168221, 0.20659417260810503), (7, 167821, 0.14981304535686124), (8, 168221, 0.18519487705768206), (8, 167813, 0.18519487705768206), (8, 167821, 0.17239075055827144), (9, 174442, 0.38214772459818913), (9, 173084, 0.3331081164241725), (9, 174727, 0.3331081164241725), (10, 167862, 0.36134119657110136), (10, 173869, 0.3433337254690264), (10, 167863, 0.33635165727563704), (11, 172411, 0.3559313570042558), (11, 172410, 0.3559313570042558), (11, 172409, 0.3375297385206946), (12, 172411, 0.2549976431286726), (12, 172410, 0.2549976431286726), (12, 172409, 0.24181428838703062), (13, 172411, 0.3406759826050772), (13, 172410, 0.3406759826050772), (13, 172409, 0.3230630655775505), (14, 175304, 0.0), (14, 175303, 0.0), (14, 170835, 0.0), (15, 172551, 0.1512802949140328), (15, 174319, 0.1512802949140328), (15, 172490, 0.1512802949140328), (16, 168101, 0.31701660715236213), (16, 167696, 0.3154514080918774), (16, 167685, 0.30259689749425683), (17, 174442, 0.4491332709489296), (17, 174439, 0.3666539506807653), (17, 173084, 0.32293878756094535), (18, 175304, 0.5655724763314649), (18, 175303, 0.5655724763314649), (18, 171090, 0.1505220573550527), (19, 174347, 0.40435413639640594), (19, 174348, 0.36277620476951594), (19, 172522, 0.3615167385296174), (20, 175300, 0.47695941041856776), (20, 175299, 0.47695941041856776), (20, 171090, 0.1452677901039006), (21, 175087, 0.5573380856174394), (21, 175086, 0.5573380856174394), (21, 171090, 0.14833054789656544), (22, 170599, 0.4270499472482939), (22, 174769, 0.3685869457793531), (22, 173095, 0.35874915627787224), (23, 171785, 0.08726996601061862), (23, 169545, 0.08709527702367681), (23, 171786, 0.0857857193638902), (24, 168101, 0.38732140736638654), (24, 167696, 0.38540909397573786), (24, 167685, 0.3697038374581079), (25, 171785, 0.07164653391724192), (25, 169545, 0.07150311847891837), (25, 171786, 0.07042800327517154), (26, 170604, 0.060576353552588925), (26, 170602, 0.059511053042438), (26, 170199, 0.05204698476315286), (27, 171618, 0.3136876656065529), (27, 175304, 0.0), (27, 170828, 0.0), (28, 174442, 0.41213123495951187), (28, 174727, 0.3866923262586867), (28, 173084, 0.3866923262586867), (29, 170599, 0.4529566803903197), (29, 174769, 0.3909470554233619), (29, 173095, 0.38051246222487906), (30, 169451, 0.6057815155154548), (30, 168626, 0.5614882169272001), (30, 172415, 0.5534270885692733), (31, 168622, 0.4211903668162318), (31, 168264, 0.37664505690533023), (31, 168623, 0.376008619753212), (32, 175304, 0.0), (32, 175303, 0.0), (32, 170835, 0.0), (33, 175304, 0.0), (33, 175303, 0.0), (33, 170835, 0.0), (34, 175304, 0.0), (34, 175303, 0.0), (34, 170835, 0.0), (35, 175304, 0.0), (35, 175303, 0.0), (35, 170835, 0.0), (36, 175304, 0.0), (36, 175303, 0.0), (36, 170835, 0.0), (37, 175304, 0.0), (37, 175303, 0.0), (37, 170835, 0.0), (38, 168222, 0.5832181226432028), (38, 168223, 0.5832181226432028), (38, 168224, 0.57230806778029), (39, 175304, 0.0), (39, 175303, 0.0), (39, 170835, 0.0), (40, 175304, 0.0), (40, 175303, 0.0), (40, 170835, 0.0), (41, 175304, 0.0), (41, 175303, 0.0), (41, 170835, 0.0), (42, 175304, 0.0), (42, 175303, 0.0), (42, 170835, 0.0), (43, 175304, 0.0), (43, 175303, 0.0), (43, 170835, 0.0), (44, 175304, 0.0), (44, 175303, 0.0), (44, 170835, 0.0), (45, 175304, 0.0), (45, 175303, 0.0), (45, 170835, 0.0), (46, 175304, 0.0), (46, 175303, 0.0), (46, 170835, 0.0), (47, 175304, 0.0), (47, 175303, 0.0), (47, 170835, 0.0), (48, 175304, 0.0), (48, 175303, 0.0), (48, 170835, 0.0), (49, 175304, 0.0), (49, 175303, 0.0), (49, 170835, 0.0), (50, 175304, 0.0), (50, 175303, 0.0), (50, 170835, 0.0), (51, 175304, 0.0), (51, 175303, 0.0), (51, 170835, 0.0), (52, 175304, 0.0), (52, 175303, 0.0), (52, 170835, 0.0), (53, 175304, 0.0), (53, 175303, 0.0), (53, 170835, 0.0), (54, 175304, 0.0), (54, 175303, 0.0), (54, 170835, 0.0), (55, 175304, 0.0), (55, 175303, 0.0), (55, 170835, 0.0), (56, 175304, 0.0), (56, 175303, 0.0), (56, 170835, 0.0), (57, 175304, 0.0), (57, 175303, 0.0), (57, 170835, 0.0), (58, 175304, 0.0), (58, 175303, 0.0), (58, 170835, 0.0), (59, 175304, 0.0), (59, 175303, 0.0), (59, 170835, 0.0), (60, 175304, 0.0), (60, 175303, 0.0), (60, 170835, 0.0), (61, 175304, 0.0), (61, 175303, 0.0), (61, 170835, 0.0), (62, 175304, 0.0), (62, 175303, 0.0), (62, 170835, 0.0), (63, 175304, 0.0), (63, 175303, 0.0), (63, 170835, 0.0), (64, 175304, 0.0), (64, 175303, 0.0), (64, 170835, 0.0), (65, 175304, 0.0), (65, 175303, 0.0), (65, 170835, 0.0), (66, 175304, 0.0), (66, 175303, 0.0), (66, 170835, 0.0), (67, 175304, 0.0), (67, 175303, 0.0), (67, 170835, 0.0), (68, 175304, 0.0), (68, 175303, 0.0), (68, 170835, 0.0), (69, 170604, 0.09338429856386571), (69, 170602, 0.09174203495660173), (69, 170199, 0.08023545293547159), (70, 167910, 0.38505571340306344), (70, 170604, 0.08592073024288296), (70, 170602, 0.08440972153416594), (71, 170604, 0.08076499237907844), (71, 170602, 0.07934465288127303), (71, 170199, 0.06939299051899435), (72, 175304, 0.0), (72, 175303, 0.0), (72, 170835, 0.0), (73, 175304, 0.0), (73, 175303, 0.0), (73, 170835, 0.0), (74, 167910, 0.3677128626066219), (74, 171116, 0.21906069079312598), (74, 171513, 0.18477419668655642), (75, 175304, 0.0), (75, 175303, 0.0), (75, 170835, 0.0), (76, 175304, 0.0), (76, 175303, 0.0), (76, 170835, 0.0), (77, 175304, 0.0), (77, 175303, 0.0), (77, 170835, 0.0), (78, 175304, 0.0), (78, 175303, 0.0), (78, 170835, 0.0), (79, 175304, 0.0), (79, 175303, 0.0), (79, 170835, 0.0), (80, 175304, 0.0), (80, 175303, 0.0), (80, 170835, 0.0), (81, 175304, 0.0), (81, 175303, 0.0), (81, 170835, 0.0), (82, 175304, 0.0), (82, 175303, 0.0), (82, 170835, 0.0), (83, 175304, 0.0), (83, 175303, 0.0), (83, 170835, 0.0), (84, 175304, 0.0), (84, 175303, 0.0), (84, 170835, 0.0), (85, 175304, 0.0), (85, 175303, 0.0), (85, 170835, 0.0), (86, 175304, 0.0), (86, 175303, 0.0), (86, 170835, 0.0), (87, 175304, 0.0), (87, 175303, 0.0), (87, 170835, 0.0), (88, 175304, 0.0), (88, 175303, 0.0), (88, 170835, 0.0), (89, 175304, 0.0), (89, 175303, 0.0), (89, 170835, 0.0), (90, 175304, 0.0), (90, 175303, 0.0), (90, 170835, 0.0), (91, 175304, 0.0), (91, 175303, 0.0), (91, 170835, 0.0), (92, 175304, 0.0), (92, 175303, 0.0), (92, 170835, 0.0), (93, 175304, 0.0), (93, 175303, 0.0), (93, 170835, 0.0), (94, 175304, 0.0), (94, 175303, 0.0), (94, 170835, 0.0), (95, 175304, 0.0), (95, 175303, 0.0), (95, 170835, 0.0), (96, 175304, 0.0), (96, 175303, 0.0), (96, 170835, 0.0), (97, 175304, 0.0), (97, 175303, 0.0), (97, 170835, 0.0), (98, 175304, 0.0), (98, 175303, 0.0), (98, 170835, 0.0), (99, 175304, 0.0), (99, 175303, 0.0), (99, 170835, 0.0), (100, 175304, 0.0), (100, 175303, 0.0), (100, 170835, 0.0), (101, 175304, 0.0), (101, 175303, 0.0), (101, 170835, 0.0), (102, 175304, 0.0), (102, 175303, 0.0), (102, 170835, 0.0), (103, 175304, 0.0), (103, 175303, 0.0), (103, 170835, 0.0), (104, 175304, 0.0), (104, 175303, 0.0), (104, 170835, 0.0), (105, 175304, 0.0), (105, 175303, 0.0), (105, 170835, 0.0), (106, 175304, 0.0), (106, 175303, 0.0), (106, 170835, 0.0), (107, 175304, 0.0), (107, 175303, 0.0), (107, 170835, 0.0), (108, 175304, 0.0), (108, 175303, 0.0), (108, 170835, 0.0), (109, 175304, 0.0), (109, 175303, 0.0), (109, 170835, 0.0), (110, 175304, 0.0), (110, 175303, 0.0), (110, 170835, 0.0), (111, 175304, 0.0), (111, 175303, 0.0), (111, 170835, 0.0), (112, 175304, 0.0), (112, 175303, 0.0), (112, 170835, 0.0), (113, 175304, 0.0), (113, 175303, 0.0), (113, 170835, 0.0), (114, 175304, 0.0), (114, 175303, 0.0), (114, 170835, 0.0), (115, 175304, 0.0), (115, 175303, 0.0), (115, 170835, 0.0), (116, 175304, 0.0), (116, 175303, 0.0), (116, 170835, 0.0), (117, 175304, 0.0), (117, 175303, 0.0), (117, 170835, 0.0), (118, 175304, 0.0), (118, 175303, 0.0), (118, 170835, 0.0), (119, 175304, 0.0), (119, 175303, 0.0), (119, 170835, 0.0), (120, 175304, 0.0), (120, 175303, 0.0), (120, 170835, 0.0), (121, 175304, 0.0), (121, 175303, 0.0), (121, 170835, 0.0)]

[(0, 174193, 0.3337451870068601), (0, 174194, 0.31204609675998063), (0, 173681, 0.0), (1, 174193, 0.3774985099595599), (1, 174194, 0.35295471261183475), (1, 173681, 0.0), (2, 174223, 0.2925246446615436), (2, 171982, 0.2925246446615436), (2, 175181, 0.0), (3, 175181, 0.0), (3, 173681, 0.0), (3, 173695, 0.0), (4, 175181, 0.0), (4, 173681, 0.0), (4, 173695, 0.0), (5, 173698, 0.4067354090750962), (5, 173699, 0.38420089128405865), (5, 175181, 0.0), (6, 173675, 0.6608162461713578), (6, 171995, 0.608056766543318), (6, 175181, 0.0), (7, 175181, 0.0), (7, 173681, 0.0), (7, 173695, 0.0), (8, 175181, 0.0), (8, 173681, 0.0), (8, 173695, 0.0), (9, 174193, 0.30373091920236467), (9, 174194, 0.2839832647548286), (9, 173681, 0.0), (10, 174186, 0.2424875847014883), (10, 175165, 0.24040603581851358), (10, 174187, 0.233273353044095), (11, 175181, 0.0), (11, 173681, 0.0), (11, 173695, 0.0), (12, 175181, 0.0), (12, 173681, 0.0), (12, 173695, 0.0), (13, 175181, 0.0), (13, 173681, 0.0), (13, 173695, 0.0), (14, 175181, 0.0), (14, 173681, 0.0), (14, 173695, 0.0), (15, 175181, 0.0), (15, 173681, 0.0), (15, 173695, 0.0), (16, 175181, 0.0), (16, 173681, 0.0), (16, 173695, 0.0), (17, 175181, 0.0), (17, 173681, 0.0), (17, 173695, 0.0), (18, 175156, 0.25652548994813434), (18, 175159, 0.24237440146358477), (18, 173706, 0.24237440146358477), (19, 175156, 0.20698913547603445), (19, 175159, 0.19557069291871196), (19, 173706, 0.19557069291871196), (20, 175156, 0.20698913547603445), (20, 175159, 0.19557069291871196), (20, 173706, 0.19557069291871196), (21, 175156, 0.20698913547603445), (21, 175159, 0.19557069291871196), (21, 173706, 0.19557069291871196), (22, 175181, 0.0), (22, 173681, 0.0), (22, 173695, 0.0), (23, 175163, 0.45506156345469206), (23, 174248, 0.4298496132067269), (23, 174195, 0.058703516912558505), (24, 175181, 0.0), (24, 173681, 0.0), (24, 173695, 0.0), (25, 175181, 0.0), (25, 173681, 0.0), (25, 173695, 0.0), (26, 174188, 0.23611061921424714), (26, 175181, 0.0), (26, 173688, 0.0), (27, 173697, 0.5373826400604285), (27, 175143, 0.3326964301590582), (27, 174195, 0.07278572966214958), (28, 175181, 0.0), (28, 173681, 0.0), (28, 173695, 0.0), (29, 175181, 0.0), (29, 173681, 0.0), (29, 173695, 0.0), (30, 175181, 0.0), (30, 173681, 0.0), (30, 173695, 0.0), (31, 175181, 0.0), (31, 173681, 0.0), (31, 173695, 0.0), (32, 175181, 0.0), (32, 173681, 0.0), (32, 173695, 0.0), (33, 175181, 0.0), (33, 173681, 0.0), (33, 173695, 0.0), (34, 168149, 0.42877858541747654), (34, 175119, 0.3364197249596239), (34, 175120, 0.31121397488807734), (35, 175181, 0.0), (35, 173681, 0.0), (35, 173695, 0.0), (36, 174214, 0.32807437830689257), (36, 171975, 0.27517963342614843), (36, 171974, 0.2734629318708582), (37, 175181, 0.0), (37, 173681, 0.0), (37, 173695, 0.0), (38, 175181, 0.0), (38, 173681, 0.0), (38, 173695, 0.0), (39, 175181, 0.0), (39, 173681, 0.0), (39, 173695, 0.0), (40, 168149, 0.42877858541747654), (40, 175119, 0.3364197249596239), (40, 175120, 0.31121397488807734), (41, 175181, 0.0), (41, 173681, 0.0), (41, 173695, 0.0), (42, 175181, 0.0), (42, 173681, 0.0), (42, 173695, 0.0), (43, 175181, 0.0), (43, 173681, 0.0), (43, 173695, 0.0), (44, 175181, 0.0), (44, 173681, 0.0), (44, 173695, 0.0), (45, 171952, 0.5284770106129939), (45, 174185, 0.4862834776348512), (45, 174218, 0.3494965660605484), (46, 175181, 0.0), (46, 173681, 0.0), (46, 173695, 0.0), (47, 175176, 0.5310947919873671), (47, 175177, 0.4886922556987094), (47, 175181, 0.0), (48, 175181, 0.0), (48, 173681, 0.0), (48, 173695, 0.0), (49, 175181, 0.0), (49, 173681, 0.0), (49, 173695, 0.0), (50, 175181, 0.0), (50, 173681, 0.0), (50, 173695, 0.0), (51, 173678, 0.33775154097107807), (51, 173679, 0.3174833306230905), (51, 175125, 0.27116969714438355), (52, 171948, 0.38477714269773616), (52, 174228, 0.36490742278707844), (52, 175123, 0.35668143646538725), (53, 175181, 0.0), (53, 173681, 0.0), (53, 173695, 0.0), (54, 174186, 0.2550328737011008), (54, 175165, 0.25284363422301426), (54, 174187, 0.2453419364045562), (55, 174195, 0.06799345299333834), (55, 168149, 0.06795635847877872), (55, 173702, 0.05730873480759719), (56, 175181, 0.0), (56, 173681, 0.0), (56, 173695, 0.0), (57, 175181, 0.0), (57, 173681, 0.0), (57, 173695, 0.0), (58, 175181, 0.0), (58, 173681, 0.0), (58, 173695, 0.0), (59, 174193, 0.3471091219001149), (59, 174194, 0.3245411495222215), (59, 173681, 0.0), (60, 175181, 0.0), (60, 173681, 0.0), (60, 173695, 0.0), (61, 175181, 0.0), (61, 173681, 0.0), (61, 173695, 0.0), (62, 175181, 0.0), (62, 173681, 0.0), (62, 173695, 0.0), (63, 174193, 0.3527323087746462), (63, 174194, 0.32979873400242365), (63, 174211, 0.32940893167096474), (64, 173696, 0.35140949483828043), (64, 174243, 0.3365689667000569), (64, 173694, 0.0), (65, 175181, 0.0), (65, 173681, 0.0), (65, 173695, 0.0), (66, 175181, 0.0), (66, 173681, 0.0), (66, 173695, 0.0), (67, 175181, 0.0), (67, 173681, 0.0), (67, 173695, 0.0), (68, 175181, 0.0), (68, 173681, 0.0), (68, 173695, 0.0), (69, 175156, 0.28440439155241637), (69, 175159, 0.26871537869421486), (69, 173706, 0.26871537869421486), (70, 175181, 0.0), (70, 173681, 0.0), (70, 173695, 0.0), (71, 167744, 0.5861877985082231), (71, 175181, 0.0), (71, 173689, 0.0), (72, 171967, 0.3371055243910266), (72, 174204, 0.3337321160063177), (72, 171966, 0.3337321160063177), (73, 175181, 0.0), (73, 173681, 0.0), (73, 173695, 0.0), (74, 168148, 0.4673239772917529), (74, 175181, 0.0), (74, 173689, 0.0), (75, 175181, 0.0), (75, 173681, 0.0), (75, 173695, 0.0), (76, 175181, 0.0), (76, 173681, 0.0), (76, 173695, 0.0), (77, 175181, 0.0), (77, 173681, 0.0), (77, 173695, 0.0), (78, 175181, 0.0), (78, 173681, 0.0), (78, 173695, 0.0), (79, 175181, 0.0), (79, 173681, 0.0), (79, 173695, 0.0), (80, 175181, 0.0), (80, 173681, 0.0), (80, 173695, 0.0), (81, 175181, 0.0), (81, 173681, 0.0), (81, 173695, 0.0), (82, 175181, 0.0), (82, 173681, 0.0), (82, 173695, 0.0), (83, 175180, 0.5445876019001352), (83, 175179, 0.5445876019001352), (83, 171972, 0.45017228097426265), (84, 175181, 0.0), (84, 173681, 0.0), (84, 173695, 0.0), (85, 174193, 0.3337451870068601), (85, 174194, 0.31204609675998063), (85, 173681, 0.0), (86, 174223, 0.2925246446615436), (86, 171982, 0.2925246446615436), (86, 175181, 0.0), (87, 175181, 0.0), (87, 173681, 0.0), (87, 173695, 0.0), (88, 175181, 0.0), (88, 173681, 0.0), (88, 173695, 0.0), (89, 174186, 0.21863546676300566), (89, 175165, 0.21675866794800885), (89, 174187, 0.21032758641623803), (90, 175181, 0.0), (90, 173681, 0.0), (90, 173695, 0.0), (91, 175156, 0.6673230513247504), (91, 172005, 0.6271561488491191), (91, 175159, 0.241861343471792), (92, 175156, 0.6733934728776433), (92, 172005, 0.632861185106214), (92, 175159, 0.24406147773855852), (93, 175181, 0.0), (93, 173681, 0.0), (93, 173695, 0.0), (94, 174195, 0.05536509949580234), (94, 168149, 0.0553348945069552), (94, 173702, 0.04666484293586376), (95, 174195, 0.06322583207634429), (95, 168149, 0.06319133858549701), (95, 173702, 0.05329031375723614), (96, 175181, 0.0), (96, 173681, 0.0), (96, 173695, 0.0), (97, 173697, 0.5373826400604285), (97, 175143, 0.3326964301590582), (97, 174195, 0.07278572966214958), (98, 174195, 0.05772344870764859), (98, 168149, 0.05769195709758538), (98, 173702, 0.04865259327968943), (99, 175181, 0.0), (99, 173681, 0.0), (99, 173695, 0.0), (100, 175181, 0.0), (100, 173681, 0.0), (100, 173695, 0.0), (101, 175181, 0.0), (101, 173681, 0.0), (101, 173695, 0.0), (102, 175181, 0.0), (102, 173681, 0.0), (102, 173695, 0.0), (103, 175181, 0.0), (103, 173681, 0.0), (103, 173695, 0.0), (104, 175181, 0.0), (104, 173681, 0.0), (104, 173695, 0.0), (105, 175181, 0.0), (105, 173681, 0.0), (105, 173695, 0.0), (106, 175181, 0.0), (106, 173681, 0.0), (106, 173695, 0.0), (107, 175181, 0.0), (107, 173681, 0.0), (107, 173695, 0.0), (108, 175181, 0.0), (108, 173681, 0.0), (108, 173695, 0.0), (109, 175181, 0.0), (109, 173681, 0.0), (109, 173695, 0.0), (110, 175181, 0.0), (110, 173681, 0.0), (110, 173695, 0.0), (111, 175181, 0.0), (111, 173681, 0.0), (111, 173695, 0.0), (112, 175181, 0.0), (112, 173681, 0.0), (112, 173695, 0.0), (113, 175181, 0.0), (113, 173681, 0.0), (113, 173695, 0.0), (114, 175181, 0.0), (114, 173681, 0.0), (114, 173695, 0.0), (115, 175181, 0.0), (115, 173681, 0.0), (115, 173695, 0.0), (116, 175181, 0.0), (116, 173681, 0.0), (116, 173695, 0.0), (117, 175181, 0.0), (117, 173681, 0.0), (117, 173695, 0.0), (118, 174188, 0.17700770892075646), (118, 175181, 0.0), (118, 173688, 0.0), (119, 175181, 0.0), (119, 173681, 0.0), (119, 173695, 0.0), (120, 175181, 0.0), (120, 173681, 0.0), (120, 173695, 0.0), (121, 175153, 0.3087282305012273), (121, 172004, 0.28865566617307753), (121, 175154, 0.24231288478757035), (122, 175181, 0.0), (122, 173681, 0.0), (122, 173695, 0.0), (123, 175181, 0.0), (123, 173681, 0.0), (123, 173695, 0.0), (124, 175181, 0.0), (124, 173681, 0.0), (124, 173695, 0.0), (125, 174182, 0.5052126265866168), (125, 174183, 0.36735856492214697), (125, 175181, 0.0), (126, 175181, 0.0), (126, 173681, 0.0), (126, 173695, 0.0), (127, 175181, 0.0), (127, 173681, 0.0), (127, 173695, 0.0), (128, 175181, 0.0), (128, 173681, 0.0), (128, 173695, 0.0), (129, 175181, 0.0), (129, 173681, 0.0), (129, 173695, 0.0), (130, 175181, 0.0), (130, 173681, 0.0), (130, 173695, 0.0), (131, 175181, 0.0), (131, 173681, 0.0), (131, 173695, 0.0), (132, 175181, 0.0), (132, 173681, 0.0), (132, 173695, 0.0), (133, 175181, 0.0), (133, 173681, 0.0), (133, 173695, 0.0), (134, 175181, 0.0), (134, 173681, 0.0), (134, 173695, 0.0), (135, 175181, 0.0), (135, 173681, 0.0), (135, 173695, 0.0), (136, 175181, 0.0), (136, 173681, 0.0), (136, 173695, 0.0), (137, 175181, 0.0), (137, 173681, 0.0), (137, 173695, 0.0), (138, 175181, 0.0), (138, 173681, 0.0), (138, 173695, 0.0), (139, 175181, 0.0), (139, 173681, 0.0), (139, 173695, 0.0), (140, 175181, 0.0), (140, 173681, 0.0), (140, 173695, 0.0), (141, 175181, 0.0), (141, 173681, 0.0), (141, 173695, 0.0), (142, 175181, 0.0), (142, 173681, 0.0), (142, 173695, 0.0), (143, 174195, 0.0947716102210493), (143, 168149, 0.09471990661253382), (143, 173702, 0.07987888301509276), (144, 175181, 0.0), (144, 173681, 0.0), (144, 173695, 0.0), (145, 175181, 0.0), (145, 173681, 0.0), (145, 173695, 0.0), (146, 175181, 0.0), (146, 173681, 0.0), (146, 173695, 0.0), (147, 175181, 0.0), (147, 173681, 0.0), (147, 173695, 0.0), (148, 175181, 0.0), (148, 173681, 0.0), (148, 173695, 0.0), (149, 175181, 0.0), (149, 173681, 0.0), (149, 173695, 0.0), (150, 175181, 0.0), (150, 173681, 0.0), (150, 173695, 0.0), (151, 175181, 0.0), (151, 173681, 0.0), (151, 173695, 0.0), (152, 175181, 0.0), (152, 173681, 0.0), (152, 173695, 0.0), (153, 175181, 0.0), (153, 173681, 0.0), (153, 173695, 0.0), (154, 175181, 0.0), (154, 173681, 0.0), (154, 173695, 0.0), (155, 175181, 0.0), (155, 173681, 0.0), (155, 173695, 0.0), (156, 175181, 0.0), (156, 173681, 0.0), (156, 173695, 0.0), (157, 175181, 0.0), (157, 173681, 0.0), (157, 173695, 0.0), (158, 175181, 0.0), (158, 173681, 0.0), (158, 173695, 0.0), (159, 175181, 0.0), (159, 173681, 0.0), (159, 173695, 0.0), (160, 175181, 0.0), (160, 173681, 0.0), (160, 173695, 0.0), (161, 175181, 0.0), (161, 173681, 0.0), (161, 173695, 0.0), (162, 175181, 0.0), (162, 173681, 0.0), (162, 173695, 0.0), (163, 175181, 0.0), (163, 173681, 0.0), (163, 173695, 0.0), (164, 175181, 0.0), (164, 173681, 0.0), (164, 173695, 0.0), (165, 175181, 0.0), (165, 173681, 0.0), (165, 173695, 0.0), (166, 175181, 0.0), (166, 173681, 0.0), (166, 173695, 0.0), (167, 175181, 0.0), (167, 173681, 0.0), (167, 173695, 0.0), (168, 175181, 0.0), (168, 173681, 0.0), (168, 173695, 0.0), (169, 175181, 0.0), (169, 173681, 0.0), (169, 173695, 0.0), (170, 175181, 0.0), (170, 173681, 0.0), (170, 173695, 0.0), (171, 175181, 0.0), (171, 173681, 0.0), (171, 173695, 0.0), (172, 175181, 0.0), (172, 173681, 0.0), (172, 173695, 0.0), (173, 175181, 0.0), (173, 173681, 0.0), (173, 173695, 0.0), (174, 175181, 0.0), (174, 173681, 0.0), (174, 173695, 0.0), (175, 175181, 0.0), (175, 173681, 0.0), (175, 173695, 0.0), (176, 175181, 0.0), (176, 173681, 0.0), (176, 173695, 0.0), (177, 175181, 0.0), (177, 173681, 0.0), (177, 173695, 0.0)]

[(0, 173423, 0.24683044866117768), (0, 171287, 0.24683044866117768), (0, 172188, 0.24683044866117768), (1, 173423, 0.2632553089549685), (1, 171287, 0.2632553089549685), (1, 172188, 0.2632553089549685), (2, 173428, 0.38166665811798894), (2, 172184, 0.38166665811798894), (2, 173436, 0.32133327206990947), (3, 172183, 0.3573309474309563), (3, 172204, 0.3573309474309563), (3, 172203, 0.2964553845628434), (4, 172189, 0.38510736606541424), (4, 173423, 0.2055143201769692), (4, 171287, 0.2055143201769692), (5, 172189, 0.46246239207270423), (5, 173428, 0.45328039297228406), (5, 172184, 0.45328039297228406), (6, 172189, 0.4669416302865514), (6, 172183, 0.43588691457838), (6, 172204, 0.43588691457838), (7, 172189, 0.4910339609077993), (7, 173423, 0.2620425355422299), (7, 171287, 0.2620425355422299), (8, 173423, 0.19563321776209192), (8, 171287, 0.19563321776209192), (8, 172188, 0.19563321776209192), (9, 173423, 0.3062756866596848), (9, 171287, 0.3062756866596848), (9, 172188, 0.3062756866596848), (10, 172191, 0.5041854238733395), (10, 173423, 0.2382503060502627), (10, 171287, 0.2382503060502627), (11, 173467, 0.0), (11, 170887, 0.0), (11, 170907, 0.0), (12, 172189, 0.5607191738662827), (12, 173423, 0.2992303704929575), (12, 171287, 0.2992303704929575), (13, 173467, 0.0), (13, 170887, 0.0), (13, 170907, 0.0), (14, 173423, 0.2348211590298863), (14, 171287, 0.2348211590298863), (14, 172188, 0.2348211590298863), (15, 173467, 0.0), (15, 170887, 0.0), (15, 170907, 0.0), (16, 173467, 0.0), (16, 170887, 0.0), (16, 170907, 0.0), (17, 173467, 0.0), (17, 170887, 0.0), (17, 170907, 0.0)]
[(0, 173467, 0.0), (0, 170887, 0.0), (0, 170907, 0.0), (1, 173467, 0.0), (1, 170887, 0.0), (1, 170907, 0.0), (2, 173467, 0.0), (2, 170887, 0.0), (2, 170907, 0.0), (3, 173467, 0.0), (3, 170887, 0.0), (3, 170907, 0.0), (4, 173467, 0.0), (4, 170887, 0.0), (4, 170907, 0.0), (5, 173467, 0.0), (5, 170887, 0.0), (5, 170907, 0.0), (6, 173467, 0.0), (6, 170887, 0.0), (6, 170907, 0.0), (7, 173467, 0.0), (7, 170887, 0.0), (7, 170907, 0.0), (8, 173467, 0.0), (8, 170887, 0.0), (8, 170907, 0.0), (9, 173467, 0.0), (9, 170887, 0.0), (9, 170907, 0.0), (10, 173467, 0.0), (10, 170887, 0.0), (10, 170907, 0.0), (11, 173467, 0.0), (11, 170887, 0.0), (11, 170907, 0.0), (12, 173467, 0.0), (12, 170887, 0.0), (12, 170907, 0.0), (13, 173467, 0.0), (13, 170887, 0.0), (13, 170907, 0.0), (14, 170887, 0.30582848273040975), (14, 170847, 0.2523632425993202), (14, 171248, 0.2354012129870698), (15, 170887, 0.4128952687795795), (15, 170847, 0.3407125064115932), (15, 171248, 0.31781227909048065), (16, 173467, 0.0), (16, 170887, 0.0), (16, 170907, 0.0)]
[(0, 171412, 0.27053262137087947), (0, 173568, 0.11007947250529791), (0, 172367, 0.0834581254482559), (1, 171412, 0.29739943170099425), (1, 173568, 0.12101155268865016), (1, 172367, 0.09174641842957168), (2, 171401, 0.405685720585344), (2, 173566, 0.26211611044548977), (2, 172327, 0.2327945527607873), (3, 167704, 0.4496333036586002), (3, 172345, 0.4172688247751947), (3, 171415, 0.06472636783404662), (4, 172341, 0.276872341883919), (4, 172340, 0.2647187806395963), (4, 173578, 0.2647187806395963), (5, 171415, 0.06309682910542042), (5, 173589, 0.06309682910542042), (5, 173572, 0.05893918485533074), (6, 173577, 0.4135610629144114), (6, 172341, 0.2160910532358289), (6, 172340, 0.20660554149427354), (7, 172341, 0.3421382243720409), (7, 172340, 0.3271197583322919), (7, 173578, 0.3271197583322919), (8, 171410, 0.3844742755646172), (8, 167737, 0.31208005617905027), (8, 171015, 0.06666981389763948), (9, 171411, 0.28991849279959614), (9, 171426, 0.24592246841005982), (9, 173588, 0.2426987856000369), (10, 171412, 0.5624596057843043), (10, 173568, 0.1956981871951029), (10, 173595, 0.18487107266473646), (11, 171015, 0.4143669945522867), (11, 171422, 0.2511686183486122), (11, 172368, 0.249408656998728), (12, 171016, 0.4574901827239991), (12, 171006, 0.29430916470576357), (12, 171015, 0.07933114718121094), (13, 171413, 0.4380390685685856), (13, 171443, 0.3981583842933832), (13, 167737, 0.3473737542374175), (14, 172339, 0.3429153612040531), (14, 171421, 0.29565029548464533), (14, 173570, 0.28189493330525933), (15, 171431, 0.25268010504846783), (15, 169052, 0.2027232452164601), (15, 171415, 0.19154226335067678), (16, 171412, 0.2629749088147675), (16, 171407, 0.18432927500661267), (16, 173568, 0.10700424628190308), (17, 171412, 0.3203262862094437), (17, 171407, 0.22452907149456433), (17, 173568, 0.1303404685055561)]
[(0, 174808, 0.0), (0, 171551, 0.0), (0, 171544, 0.0), (1, 174808, 0.0), (1, 171551, 0.0), (1, 171544, 0.0), (2, 174808, 0.0), (2, 171551, 0.0), (2, 171544, 0.0), (3, 174808, 0.0), (3, 171551, 0.0), (3, 171544, 0.0), (4, 174808, 0.0), (4, 171551, 0.0), (4, 171544, 0.0), (5, 174808, 0.0), (5, 171551, 0.0), (5, 171544, 0.0), (6, 174808, 0.0), (6, 171551, 0.0), (6, 171544, 0.0), (7, 171325, 0.4072675546336655), (7, 174808, 0.0), (7, 171551, 0.0), (8, 174808, 0.0), (8, 171551, 0.0), (8, 171544, 0.0), (9, 174808, 0.0), (9, 171551, 0.0), (9, 171544, 0.0), (10, 171150, 0.25208292897534157), (10, 171319, 0.22987687861905318), (10, 172911, 0.20292607150684688), (11, 171150, 0.2788874024536603), (11, 171319, 0.2543201391018994), (11, 172911, 0.22450359967931885), (12, 171150, 0.29872384644155253), (12, 171319, 0.2724091856127974), (12, 172911, 0.24047188308308054), (13, 171150, 0.29872384644155253), (13, 171319, 0.2724091856127974), (13, 172911, 0.24047188308308054), (14, 171150, 0.2788874024536603), (14, 171319, 0.2543201391018994), (14, 172911, 0.22450359967931885), (15, 171321, 0.49649334192496064), (15, 174808, 0.0), (15, 171551, 0.0), (16, 170917, 0.556076185398242), (16, 170921, 0.27464129462766607), (16, 171552, 0.0), (17, 170926, 0.4008825518800427), (17, 171543, 0.0), (17, 171545, 0.0), (18, 174808, 0.0), (18, 171551, 0.0), (18, 171544, 0.0), (19, 170922, 0.6761785260548806), (19, 170921, 0.3654615599943564), (19, 170920, 0.2772449918549512), (20, 174808, 0.0), (20, 171551, 0.0), (20, 171544, 0.0), (21, 172231, 0.4964933419249605), (21, 174808, 0.0), (21, 171562, 0.0), (22, 170933, 0.3911412756467551), (22, 170931, 0.3837467186445157), (22, 174527, 0.3641144336300737), (23, 171326, 0.40088255188004257), (23, 174808, 0.0), (23, 171551, 0.0), (24, 171159, 0.3095618477894527), (24, 172918, 0.25543432278235), (24, 172898, 0.19324392016721745), (25, 171159, 0.3095618477894527), (25, 172918, 0.25543432278235), (25, 172898, 0.19324392016721745), (26, 171606, 0.4292489592106002), (26, 174531, 0.38085151764775477), (26, 172885, 0.28640082940171446), (27, 173469, 0.4033466826878081), (27, 172241, 0.4033466826878081), (27, 172237, 0.4033466826878081), (28, 171584, 0.21748802722160374), (28, 174523, 0.16344697670078628), (28, 171595, 0.1610175650684902), (29, 171606, 0.2572193026537763), (29, 174531, 0.22821805314133584), (29, 172885, 0.17162026846529613), (30, 171159, 0.23696753176512564), (30, 172918, 0.1955332720426158), (30, 172898, 0.14792693323690237), (31, 171159, 0.20758184793591866), (31, 172918, 0.17128573539683706), (31, 171192, 0.17033064289850508), (32, 172882, 0.3000624306407176), (32, 171595, 0.28336331081806526), (32, 171825, 0.24290966101288666), (33, 174808, 0.0), (33, 171551, 0.0), (33, 171544, 0.0), (34, 171606, 0.2810885976782087), (34, 174531, 0.2493961062039572), (34, 172885, 0.18754619151192056), (35, 174808, 0.0), (35, 171551, 0.0), (35, 171544, 0.0), (36, 174808, 0.0), (36, 171551, 0.0), (36, 171544, 0.0)]
[(0, 174831, 0.3226557228168071), (0, 174116, 0.19596853733708622), (0, 174859, 0.09206198054962078)]
[(0, 173137, 0.19926748955856105), (0, 174782, 0.16139897719960178), (0, 168760, 0.16082633821488296), (1, 169592, 0.3355433318577655), (1, 170271, 0.25496845668534285), (1, 170272, 0.25496845668534285), (2, 167587, 0.2611103525193883), (2, 167984, 0.21575852700557607), (2, 174650, 0.1974368569136759), (3, 170274, 0.31806975967158607), (3, 170271, 0.2793747373786276), (3, 170272, 0.2793747373786276), (4, 173141, 0.2540373151637604), (4, 169878, 0.16154844333292243), (4, 170674, 0.15407599602323505), (5, 174806, 0.0), (5, 168794, 0.0), (5, 168780, 0.0), (6, 167743, 0.4315975538692876), (6, 169878, 0.16154844333292243), (6, 170674, 0.15407599602323505), (7, 174806, 0.0), (7, 168794, 0.0), (7, 168780, 0.0), (8, 168779, 0.40691579083555407), (8, 168784, 0.37544879880535575), (8, 169648, 0.3413328922920114), (9, 169640, 0.6298081668438885), (9, 167546, 0.31806067720267606), (9, 167564, 0.27303762104966345), (10, 174806, 0.0), (10, 168794, 0.0), (10, 168780, 0.0), (11, 174806, 0.0), (11, 168794, 0.0), (11, 168780, 0.0), (12, 174806, 0.0), (12, 168794, 0.0), (12, 168780, 0.0), (13, 167953, 0.45785668451089073), (13, 170681, 0.40338568457501084), (13, 167743, 0.36864554143829964), (14, 167953, 0.23287455581641672), (14, 170681, 0.2051695766295455), (14, 167743, 0.1875000838042902), (15, 170679, 0.14886987130500484), (15, 174806, 0.0), (15, 168786, 0.0), (16, 170679, 0.15059656950185318), (16, 174806, 0.0), (16, 168786, 0.0), (17, 174806, 0.0), (17, 168794, 0.0), (17, 168780, 0.0)]
Matching MyFCD → USDA ...

[(0, 171867, 0.43050039327062756), (0, 171847, 0.4167534003354952), (0, 175016, 0.40908785177199897), (1, 172790, 0.3557291186960162), (1, 172738, 0.3557291186960162), (1, 171867, 0.34667201076128945), (2, 171867, 0.9436782778330064), (2, 174941, 0.2924812438685637), (2, 171866, 0.2764820410017426), (3, 174980, 0.33990205435903725), (3, 171867, 0.26586034110795487), (3, 174941, 0.20188404043735014), (4, 175084, 0.0), (4, 170289, 0.0), (4, 170688, 0.0), (5, 172680, 0.47126728726295075), (5, 172817, 0.4602313836688168), (5, 174075, 0.4007365128530438), (6, 167944, 0.3387422598301956), (6, 167925, 0.3121080435455591), (6, 174084, 0.28335634693017037), (7, 171847, 0.26335888142652053), (7, 175016, 0.2585147930673665), (7, 172782, 0.23326249572908492), (8, 175084, 0.0), (8, 170289, 0.0), (8, 170688, 0.0), (9, 167943, 0.4317962738728042), (9, 174099, 0.1899909415372862), (9, 171861, 0.16858638958215394), (10, 168891, 0.21481061031797485), (10, 168890, 0.2054313169918756), (10, 168889, 0.20104493115424352), (11, 174964, 0.6018899997185151), (11, 172730, 0.5953282226943205), (11, 172729, 0.5953282226943205), (12, 175078, 0.44727308227525137), (12, 167929, 0.43771979515934073), (12, 174908, 0.3586909621317182), (13, 175078, 0.39984234417319325), (13, 167929, 0.3913021282148482), (13, 172737, 0.34255621547051346), (14, 174096, 0.2894862978343728), (14, 174923, 0.282633669626547), (14, 168873, 0.27261355816927807), (15, 174096, 0.43686675226611743), (15, 174097, 0.3213441345949694), (15, 175069, 0.27315786364176353), (16, 174996, 0.3385612967804645), (16, 174096, 0.32477985503151074), (16, 175069, 0.2895895142260073), (17, 174098, 0.22720413557233918), (17, 174970, 0.22396362025672398), (17, 174096, 0.20942740983517155), (18, 171838, 0.4527002184555672), (18, 171852, 0.3969533386908631), (18, 168873, 0.3419527307579748), (19, 167531, 0.37992149933665664), (19, 172747, 0.275888393635807), (19, 167530, 0.2558466123454452)]
[(0, 169711, 0.24285447033956292), (0, 168883, 0.20257779246611812), (0, 168914, 0.07990895880795457), (1, 169714, 0.1146826225225229), (1, 168898, 0.10558240328902004), (1, 168914, 0.07025388628306005), (2, 169723, 0.16584849805192833), (2, 168914, 0.07733207587385492), (2, 169742, 0.07733207587385492), (3, 169723, 0.17011195418255393), (3, 173265, 0.0), (3, 168923, 0.0), (4, 173265, 0.0), (4, 168932, 0.0), (4, 168930, 0.0), (5, 169711, 0.3392296811031024), (5, 168883, 0.28296946661416517), (5, 169723, 0.2393839828063507), (6, 169723, 0.22865199874318753), (6, 168890, 0.1807825658025518), (6, 168891, 0.18078256580255178)]
[(0, 175084, 0.0), (0, 170289, 0.0), (0, 170688, 0.0), (1, 175084, 0.0), (1, 170289, 0.0), (1, 170688, 0.0), (2, 174937, 0.39297706875564237), (2, 172784, 0.2676791707624331), (2, 172825, 0.16404156329464722), (3, 172706, 0.5137210249778938), (3, 172707, 0.4621396992383214), (3, 174943, 0.3448286729351911), (4, 174078, 0.308805326449627), (4, 167590, 0.2867929667399009), (4, 172802, 0.208281258592935), (5, 174078, 0.25741515842887847), (5, 167590, 0.23906600905629827), (5, 172802, 0.17361991062421758), (6, 175084, 0.0), (6, 170289, 0.0), (6, 170688, 0.0), (7, 174945, 0.24383981413113529), (7, 172709, 0.24316615682870857), (7, 172697, 0.2394817176696542), (8, 175084, 0.0), (8, 170289, 0.0), (8, 170688, 0.0), (9, 171849, 0.20313468240433405), (9, 175034, 0.18514927483496368), (9, 172799, 0.1817444976627261), (10, 175084, 0.0), (10, 170289, 0.0), (10, 170688, 0.0), (11, 175084, 0.0), (11, 170289, 0.0), (11, 170688, 0.0), (12, 175084, 0.0), (12, 170289, 0.0), (12, 170688, 0.0), (13, 168891, 0.245467514345127), (13, 168890, 0.23475986655315115), (13, 168889, 0.2297526527440284), (14, 174075, 0.37869638219597995), (14, 171844, 0.3738261126994385), (14, 171835, 0.0), (15, 172699, 0.4054564956881812), (15, 167944, 0.37993850638375176), (15, 167925, 0.3506958548610047), (16, 174934, 0.2853970792871496), (16, 174935, 0.2761095410212958), (16, 172697, 0.24910669204393426), (17, 169723, 0.11092462583284235), (17, 174947, 0.10699791561754658), (17, 175055, 0.10498314948610672), (18, 167512, 0.1738815299198545), (18, 169723, 0.1123526937290745), (18, 174947, 0.10837543018755232), (19, 172754, 0.8385620336691177), (19, 172753, 0.7947297743491133), (19, 172824, 0.7845602239595881), (20, 172738, 0.5748646608163199), (20, 172790, 0.5748646608163199), (20, 172825, 0.33983451426968003), (21, 172790, 0.6122577526815617), (21, 172738, 0.6122577526815617), (21, 172719, 0.3576997182079611), (22, 172706, 0.3122278685081413), (22, 172707, 0.28087792056473393), (22, 172673, 0.21025467273343476), (23, 174943, 0.17076774951904394), (23, 174942, 0.16937450477623267), (23, 174951, 0.1615748193239682)]
[(0, 169742, 0.11444244707733572), (0, 168914, 0.11444244707733572), (0, 173900, 0.10952023968905486), (1, 169742, 0.13927164375214976), (1, 168914, 0.13927164375214976), (1, 173900, 0.13328152442700458), (2, 169742, 0.3864771798695371), (2, 168914, 0.3864771798695371), (2, 173900, 0.36985466891544794), (3, 169742, 0.10992116098415984), (3, 168914, 0.10992116098415984), (3, 173900, 0.10519341560172304), (4, 169742, 0.20323461925021422), (4, 168914, 0.20323461925021422), (4, 173900, 0.19449343125593926), (5, 169742, 0.1968247682201557), (5, 168914, 0.1968247682201557), (5, 173900, 0.1883592700324489), (6, 174664, 0.0), (6, 169733, 0.0), (6, 169724, 0.0), (7, 174664, 0.0), (7, 169733, 0.0), (7, 169724, 0.0), (8, 169742, 0.2297913631238423), (8, 168914, 0.2297913631238423), (8, 173900, 0.21990796081799185)]
[(0, 169711, 0.2747305087618174), (0, 168883, 0.22622121542282578), (0, 168914, 0.09624351107905638), (1, 169711, 0.21982321894369272), (1, 168883, 0.1810089312312717), (1, 169714, 0.12597644429685173), (2, 173265, 0.0), (2, 168932, 0.0), (2, 168930, 0.0), (3, 169711, 0.198426052320666), (3, 168883, 0.16338987224185902), (3, 168914, 0.06951255632644032), (4, 169711, 0.2916791484135911), (4, 168883, 0.24017722591131435), (4, 168914, 0.1021809535402233), (5, 169714, 0.11044969935862928), (5, 168898, 0.10156823489494164), (5, 168914, 0.06751702889666536)]
[(0, 168568, 0.35513578145057495), (0, 168565, 0.2989793053475401), (0, 169318, 0.26816389325754575), (1, 170419, 0.18688288628312613), (1, 170456, 0.16947302993089525), (1, 170102, 0.16875543130826806), (2, 169977, 0.21941037132278066), (2, 168515, 0.20187164754454626), (2, 170108, 0.20136143336643744), (3, 170096, 0.19241169471909117), (3, 169998, 0.18951393080545076), (3, 169383, 0.18406392246506548), (4, 168577, 0.3928966353678181), (4, 170054, 0.36658824704195775), (4, 170497, 0.32223867096414416)]
[(0, 169975, 0.5502553325043597), (0, 169976, 0.4148749235610124), (0, 169977, 0.3968299990660822), (1, 168421, 0.38516045621351813), (1, 169355, 0.3412123237461057), (1, 169356, 0.3412123237461057), (2, 169253, 0.27148830019961684), (2, 170142, 0.2588219754931507), (2, 168461, 0.25241581498658944), (3, 168462, 0.4390344356929968), (3, 170531, 0.3742088110616481), (3, 168463, 0.33768739768494405), (4, 169975, 0.25979453445415096), (4, 169976, 0.19587677075783858), (4, 169977, 0.18735713908596638), (5, 170008, 0.10253687936571355), (5, 170542, 0.09983028897253605), (5, 169307, 0.09086186653397758)]
[(0, 174687, 0.0), (0, 169134, 0.0), (0, 169118, 0.0)]
[(0, 168209, 0.14863527257467712), (0, 173954, 0.14176903559603984), (0, 167757, 0.13948140697754283), (1, 173039, 0.20717454138325553), (1, 174679, 0.17360680065105374), (1, 173034, 0.16718996738296463), (2, 169911, 0.3996475788529828), (2, 174687, 0.0), (2, 168206, 0.0), (3, 174687, 0.0), (3, 168173, 0.0), (3, 168197, 0.0), (4, 167787, 0.5323200350443953), (4, 174687, 0.0), (4, 168206, 0.0)]
[(0, 173086, 0.0415320760069078), (0, 174730, 0.0415320760069078), (0, 170200, 0.04026376200038173), (1, 171116, 0.13287781671707585), (1, 171513, 0.10747799373538389), (1, 171468, 0.105736906197254)]
[(0, 170199, 0.026040882580794525), (0, 170200, 0.026040882580794525), (0, 174730, 0.024528905466368652), (1, 170199, 0.03701905389226202), (1, 170200, 0.03701905389226202), (1, 174730, 0.03486966582489758), (2, 171116, 0.1065597346562697), (2, 171513, 0.08763361750932026), (2, 171468, 0.08700817711201807), (3, 171116, 0.10655973465626972), (3, 171513, 0.08763361750932029), (3, 171468, 0.0870081771120181)]
[(0, 175181, 0.0), (0, 173681, 0.0), (0, 173695, 0.0), (1, 174219, 0.29776993529830825), (1, 171981, 0.2807307111097857), (1, 175140, 0.2642384327128574)]
[(0, 174182, 0.3060104162287178), (0, 174183, 0.224311540215316), (0, 175181, 0.0), (1, 174186, 0.228517902769846), (1, 175165, 0.22644413023933607), (1, 173714, 0.2211219784226514), (2, 175181, 0.0), (2, 173681, 0.0), (2, 173695, 0.0), (3, 174204, 0.1550944432386895), (3, 171966, 0.1550944432386895), (3, 171967, 0.15419653489734683), (4, 174215, 0.3543963253746536), (4, 172010, 0.3033556535387667), (4, 175181, 0.0), (5, 175181, 0.0), (5, 173681, 0.0), (5, 173695, 0.0)]
[(0, 173734, 0.28143113742983233), (0, 175237, 0.25372521913125184), (0, 173735, 0.22041030855492402), (1, 173755, 0.5732436111047114), (1, 174275, 0.20183903834714195), (1, 174267, 0.19436865964986313), (2, 173733, 0.22482258098508692), (2, 173732, 0.22482258098508692), (2, 174278, 0.17187433463889693), (3, 173772, 0.31120939639601597), (3, 173773, 0.29930535314211104), (3, 173771, 0.29590365599925517)]
[(0, 175258, 0.0), (0, 172475, 0.0), (0, 173744, 0.0), (1, 172438, 0.1667733246452526), (1, 174298, 0.14829987022203078), (1, 172457, 0.14774246864025456)]
[(0, 170155, 0.17956815981110272), (0, 170191, 0.17449583252231884), (0, 168597, 0.1567120831342285)]

[(0, 170881, 0.21701899829639898), (0, 172217, 0.20788759170545598), (0, 171302, 0.2071418655405877), (1, 171287, 0.2084774148016108), (1, 173423, 0.2084774148016108), (1, 172188, 0.2084774148016108)]
[(0, 173410, 0.42419070353819827), (0, 171314, 0.31672478605544235), (0, 173430, 0.2393032289368333), (1, 169081, 0.39890986580224047), (1, 171254, 0.37005249621470376), (1, 170896, 0.32122145050829015), (2, 172175, 0.6300782554207871), (2, 173418, 0.12383152288542994), (2, 169081, 0.09740997718429732), (3, 172177, 0.9240816810201111), (3, 173418, 0.0964127773013847), (3, 169081, 0.0758414838028907), (4, 172178, 0.9240816810201111), (4, 173418, 0.0964127773013847), (4, 169081, 0.0758414838028907), (5, 171295, 0.48373527800032246), (5, 173439, 0.43157184415708205), (5, 170896, 0.418836154931305), (6, 173418, 0.07071862706133589), (6, 169081, 0.055629614237426836), (6, 171251, 0.04814504465373066), (7, 173416, 0.9107945650873734), (7, 173439, 0.6203376188889134), (7, 173440, 0.5634977669624694), (8, 173418, 0.09085471391986354), (8, 169081, 0.07146932706470882), (8, 171251, 0.06185363659393312), (9, 170848, 0.6172037717484777), (9, 167705, 0.6040639999336588), (9, 171247, 0.6001457237069964), (10, 170851, 0.8466227405971294), (10, 171248, 0.5742334164564022), (10, 173418, 0.10074649083528707), (11, 170860, 0.38181348663986314), (11, 167687, 0.29542635664790023), (11, 173411, 0.2611199846162346), (12, 173418, 0.44884615141774187), (12, 169079, 0.2922747918825591), (12, 172207, 0.27568987253933924), (13, 173429, 0.2642899334145808), (13, 173427, 0.17422088109853912), (13, 173459, 0.15248989925314604), (14, 172208, 0.3569923866548287), (14, 172221, 0.27389243607916763), (14, 170910, 0.25756615460395577), (15, 170876, 0.17797680514370964), (15, 170845, 0.1583543427074652), (15, 171274, 0.15466192294875655), (16, 170874, 0.39211510970655766), (16, 171257, 0.3850151850394339), (16, 167697, 0.3778107190861559), (17, 171275, 1.0), (17, 173463, 0.3193548227512814), (17, 173445, 0.2958054301962737), (18, 172208, 0.3569923866548287), (18, 172221, 0.27389243607916763), (18, 170910, 0.25756615460395577), (19, 173418, 0.2662808181481928), (19, 170857, 0.21358553784097728), (19, 170860, 0.18096464306339483), (20, 169079, 0.4377210908458584), (20, 170888, 0.3728803007351136), (20, 168141, 0.3584948400573501), (21, 171284, 0.1158047006411966), (21, 172208, 0.11205206598918414), (21, 170905, 0.10451744187216395), (22, 170888, 0.5126675732888324), (22, 170886, 0.4925072090386555), (22, 170889, 0.42863721778544117), (23, 172229, 0.7463707980526192), (23, 172230, 0.584679264775897), (23, 172226, 0.5349905322634003), (24, 170905, 0.2973563880230969), (24, 170889, 0.24705779644486153), (24, 171286, 0.24705779644486153), (25, 170901, 0.4009712381608876), (25, 171300, 0.3872593001854302), (25, 171297, 0.2846532981099525), (26, 171275, 0.31274866926803657), (26, 172194, 0.302233234778673), (26, 171302, 0.23312889565520578)]
[(0, 173577, 0.6957552032104561), (0, 172341, 0.25508289891212355), (0, 172340, 0.24416502419478087), (1, 172354, 0.30922704339432827), (1, 173582, 0.27757517622586314), (1, 172355, 0.2767360201481312), (2, 172355, 0.3591669620214957), (2, 172350, 0.2706178775410275), (2, 172354, 0.261181626033252), (3, 168112, 0.3252628507996373), (3, 171009, 0.3061998588282627), (3, 173594, 0.28721741886384405), (4, 172339, 0.27411674180226414), (4, 169052, 0.26474037734512373), (4, 171015, 0.07709894786466903), (5, 172336, 0.8677595137618321), (5, 169867, 0.6006372576801273), (5, 171042, 0.45785482603080924), (6, 171412, 0.5488657411372901), (6, 173568, 0.2116675751546121), (6, 173595, 0.19171735295549508), (7, 172328, 0.2738765490216602), (7, 171025, 0.24929067155782023), (7, 172357, 0.23694679646016945), (8, 171422, 0.2402223751723061), (8, 172354, 0.2186957742304551), (8, 172370, 0.21560062190341817), (9, 171402, 0.5674393595096213), (9, 171008, 0.5497095637158725), (9, 172356, 0.5471397664256621), (10, 171432, 0.2194390363535439), (10, 171431, 0.15375899220143155), (10, 169052, 0.12424663434645415)]
[(0, 169597, 0.29057714973085286), (0, 169657, 0.2572756611332254), (0, 169598, 0.25295705955066333), (1, 168819, 0.20735008087537138), (1, 167577, 0.1933762142492567), (1, 168113, 0.16806105355805798), (2, 167583, 0.2503863751619134), (2, 168810, 0.22176451629846533), (2, 168758, 0.21611394094865083), (3, 170681, 0.0), (3, 168795, 0.0), (3, 168775, 0.0), (4, 170681, 0.0), (4, 168795, 0.0), (4, 168775, 0.0), (5, 170259, 0.20736993650991345), (5, 170681, 0.0), (5, 168783, 0.0), (6, 170681, 0.0), (6, 168795, 0.0), (6, 168775, 0.0), (7, 170681, 0.0), (7, 168795, 0.0), (7, 168775, 0.0), (8, 169638, 0.31377191668284676), (8, 170681, 0.0), (8, 168773, 0.0), (9, 170681, 0.0), (9, 168795, 0.0), (9, 168775, 0.0), (10, 168819, 0.3243647328520109), (10, 167577, 0.3025049414501754), (10, 168113, 0.2629035807946093), (11, 169665, 0.3634312781282461), (11, 168847, 0.27627600102622646), (11, 170681, 0.0), (12, 170681, 0.0), (12, 168795, 0.0), (12, 168775, 0.0), (13, 170681, 0.0), (13, 168795, 0.0), (13, 168775, 0.0), (14, 170681, 0.0), (14, 168795, 0.0), (14, 168775, 0.0), (15, 169640, 1.0), (15, 167546, 0.5011295945018724), (15, 167564, 0.44602840242253666), (16, 170645, 0.33124497972086914), (16, 170681, 0.0), (16, 168773, 0.0), (17, 167738, 0.3026576887202636), (17, 169652, 0.25726938775887037), (17, 168783, 0.0), (18, 170681, 0.0), (18, 168795, 0.0), (18, 168775, 0.0), (19, 170681, 0.0), (19, 168795, 0.0), (19, 168775, 0.0), (20, 169665, 0.348391302098724), (20, 168847, 0.26484279567756513), (20, 170681, 0.0), (21, 168810, 0.3321608208999712), (21, 168758, 0.3236973400055549), (21, 170664, 0.21994508764487414), (22, 168819, 0.8351032248260383), (22, 167577, 0.337933576509487), (22, 167706, 0.31961600661849043), (23, 168759, 0.1358711491219637), (23, 167985, 0.1358711491219637), (23, 168770, 0.1358711491219637), (24, 169878, 0.1576762269931447), (24, 170674, 0.1522828096841155), (24, 170656, 0.13158277114349648), (25, 169665, 0.23197853209495795), (25, 168847, 0.17634723544216593), (25, 168759, 0.13481093717687906)]
[(0, 175112, 0.1970355796735812), (0, 174116, 0.19485197186975375), (0, 171880, 0.19054858654541146), (1, 171887, 0.4274675992588435), (1, 171886, 0.4069035504356526), (1, 174824, 0.3961853384700279), (2, 174108, 0.678770968959797), (2, 174816, 0.6518995378481888), (2, 174171, 0.6051850503154134), (3, 175105, 0.14047784019268097), (3, 169044, 0.13113982506847596), (3, 171916, 0.12992482898682312), (4, 173176, 0.38898977660837813), (4, 175112, 0.22662345684590862), (4, 175115, 0.0), (5, 169044, 0.7225200056807074), (5, 173225, 0.505294505240943), (5, 173223, 0.4921470058617863), (6, 174824, 0.37753043803212705), (6, 171886, 0.32283245588940424), (6, 174176, 0.28430954063226543), (7, 174824, 0.5133804029658677), (7, 174128, 0.4815763411437865), (7, 171885, 0.4815763411437865), (8, 174824, 0.37753043803212705), (8, 171886, 0.32283245588940424), (8, 174176, 0.28430954063226543), (9, 174144, 0.10040568960466967), (9, 173230, 0.0931901679744738), (9, 173231, 0.09011135191795726), (10, 174133, 0.4890842108722149), (10, 171893, 0.4737581239890667), (10, 174134, 0.458103921256591), (11, 174867, 0.5713194149152232), (11, 174866, 0.4969980225597216), (11, 174865, 0.4821901527924498), (12, 174824, 0.3101331022456967), (12, 174176, 0.2729547208731452), (12, 171886, 0.2651998910934379), (13, 173230, 0.5376354060600643), (13, 173231, 0.5198730116282513), (13, 175088, 0.5067836160869912), (14, 174824, 0.36024463277270274), (14, 171918, 0.3097803198255504), (14, 171886, 0.3080510809279209), (15, 175093, 0.33429148579952545), (15, 174850, 0.30746170577585885), (15, 175099, 0.3038068818544869), (16, 169044, 0.8161338145729089), (16, 173225, 0.5707633405340778), (16, 173223, 0.5559123762202289), (17, 169044, 0.6459877944043908), (17, 174868, 0.5023096751382822), (17, 174854, 0.5011805006795855), (18, 169044, 0.7225200056807073), (18, 173225, 0.505294505240943), (18, 173223, 0.4921470058617863)]
[(0, 170551, 0.0), (0, 169237, 0.0), (0, 169247, 0.0), (1, 168446, 0.3963458483771946), (1, 170551, 0.0), (1, 169237, 0.0), (2, 170542, 0.1767803312948345), (2, 169307, 0.16206914403540743), (2, 169303, 0.1435372079818157), (3, 170542, 0.3824591230673547), (3, 169307, 0.3506318958113069), (3, 170108, 0.31665946064263084), (4, 170551, 0.0), (4, 169237, 0.0), (4, 169247, 0.0), (5, 169394, 0.2269817034186583), (5, 170551, 0.0), (5, 169249, 0.0), (6, 170043, 0.2154745598924551), (6, 170044, 0.14797427623846665), (6, 170551, 0.0), (7, 170043, 0.18254419409959832), (7, 170044, 0.1253597873312935), (7, 170551, 0.0), (8, 170551, 0.0), (8, 169237, 0.0), (8, 169247, 0.0)]
[(0, 170551, 0.0), (0, 169237, 0.0), (0, 169247, 0.0), (1, 170551, 0.0), (1, 169237, 0.0), (1, 169247, 0.0)]
[(0, 171649, 0.12830899597254958), (0, 174664, 0.0), (0, 169732, 0.0), (1, 173927, 0.18536222906415392), (1, 168920, 0.15710280942011126), (1, 169748, 0.13757711076893112), (2, 169711, 0.3332994492798764), (2, 168883, 0.2817378406978632), (2, 169742, 0.11792938464023935), (3, 174664, 0.0), (3, 169733, 0.0), (3, 169724, 0.0)]
[(0, 174808, 0.0), (0, 171332, 0.0), (0, 171537, 0.0), (1, 174808, 0.0), (1, 171332, 0.0), (1, 171537, 0.0), (2, 174808, 0.0), (2, 171332, 0.0), (2, 171537, 0.0), (3, 174808, 0.0), (3, 171332, 0.0), (3, 171537, 0.0), (4, 172894, 0.21841157914900042), (4, 174537, 0.20122297552680649), (4, 172897, 0.18245909892051024), (5, 174808, 0.0), (5, 171332, 0.0), (5, 171537, 0.0), (6, 174808, 0.0), (6, 171332, 0.0), (6, 171537, 0.0), (7, 170933, 0.28827277877521457), (7, 174525, 0.22795047690630316), (7, 174526, 0.21896516984301231), (8, 174808, 0.0), (8, 171332, 0.0), (8, 171537, 0.0), (9, 172879, 0.733871189396142), (9, 171584, 0.15698323180427862), (9, 174523, 0.10376768806670543), (10, 173471, 0.46300460648296166), (10, 172236, 0.31318179959234116), (10, 172235, 0.31318179959234116), (11, 171615, 0.1288312472372299), (11, 171614, 0.12795067636483864), (11, 171832, 0.11991902775712696), (12, 171615, 0.1288312472372299), (12, 171614, 0.12795067636483864), (12, 171832, 0.11991902775712696), (13, 174808, 0.0), (13, 171332, 0.0), (13, 171537, 0.0), (14, 171183, 0.14132955152683283), (14, 172894, 0.11758362888140862), (14, 171575, 0.11325606266178409), (15, 174808, 0.0), (15, 171332, 0.0), (15, 171537, 0.0), (16, 173471, 0.3245854462911556), (16, 172235, 0.2195534402197965), (16, 172236, 0.2195534402197965), (17, 171183, 0.13973284297050328), (17, 171146, 0.11950969588011132), (17, 171575, 0.111976521883832), (18, 171825, 0.15930163804721953), (18, 172240, 0.13648349325917203), (18, 170932, 0.13065876877244226), (19, 174808, 0.0), (19, 171332, 0.0), (19, 171537, 0.0), (20, 172894, 0.17476115210794205), (20, 174537, 0.16100775961911207), (20, 172897, 0.14599391874810894), (21, 174808, 0.0), (21, 171332, 0.0), (21, 171537, 0.0), (22, 171541, 0.27074212726444397), (22, 169770, 0.2389163261706167), (22, 169769, 0.23097368914136848), (23, 174808, 0.0), (23, 171332, 0.0), (23, 171537, 0.0), (24, 174808, 0.0), (24, 171332, 0.0), (24, 171537, 0.0), (25, 172894, 0.1516736994136342), (25, 174070, 0.1431246245644818), (25, 174537, 0.13973724847412514), (26, 174808, 0.0), (26, 171332, 0.0), (26, 171537, 0.0), (27, 171575, 0.267134399087412), (27, 173341, 0.2042827530652973), (27, 171174, 0.16229046434645664), (28, 172894, 0.17595925752666994), (28, 171575, 0.16948322556417084), (28, 174537, 0.16211157626789308), (29, 171146, 0.17919265794305347), (29, 171155, 0.16153355229536823), (29, 171552, 0.1511832693956127)]

In [7]:
# ─────────────────────────────────────────────────────────────────────────────
# 6. CONFIDENCE LABELLING
#    HIGH   (≥0.65) → direct value borrowing (food-specific USDA values)
#    MEDIUM (≥0.40) → borrow with flagging; recommend manual review
#    LOW    (<0.40) → category-level borrowing only (use USDA category mean)
# ─────────────────────────────────────────────────────────────────────────────
def classify_confidence(score: float) -> str:
    if score >= 0.65: return "HIGH"
    if score >= 0.40: return "MEDIUM"
    return "LOW"
 
for df in [tkpi_links, myfcd_links]:
    df["confidence"] = df["similarity_score"].apply(classify_confidence)
 
# Keep only the best match per food
tkpi_best  = (tkpi_links
              .sort_values("similarity_score", ascending=False)
              .drop_duplicates("source_food_id"))
myfcd_best = (myfcd_links
              .sort_values("similarity_score", ascending=False)
              .drop_duplicates("source_food_id"))
 
print(f"\nTKPI  matched: {len(tkpi_best)} / {len(tkpi)} foods")
print(f"MyFCD matched: {len(myfcd_best)} / {len(myfcd)} foods")
print("\nTKPI confidence:\n",  tkpi_best["confidence"].value_counts())
print("\nMyFCD confidence:\n", myfcd_best["confidence"].value_counts())

TKPI  matched: 334 / 1146 foods
MyFCD matched: 138 / 234 foods

TKPI confidence:
 confidence
LOW       198
MEDIUM    118
HIGH       18
Name: count, dtype: int64

MyFCD confidence:
 confidence
LOW       89
MEDIUM    32
HIGH      17
Name: count, dtype: int64

In [10]:
# ─────────────────────────────────────────────────────────────────────────────
# 7. VALUE BORROWING
#    Nutrients present in USDA but absent from TKPI/MyFCD schema:
#      magnesium_mg, sugars_total_g, saturated_fat_g,
#      cholesterol_mg, vitamin_b6_mg, vitamin_b12_mcg
#
#    BORROWING POLICY (based on food type + confidence):
#
#    ┌──────────────┬────────────────────────────┬────────────────────────┐
#    │ Confidence   │ Food type                  │ Action                 │
#    ├──────────────┼────────────────────────────┼────────────────────────┤
#    │ HIGH (≥0.65) │ Raw/unprocessed            │ Direct food-level borrow│
#    │ HIGH (≥0.65) │ Cooked/processed           │ Borrow + flag warning  │
#    │ MEDIUM       │ Any                        │ Borrow + flag + review │
#    │ LOW (<0.40)  │ Any                        │ Category mean only     │
#    └──────────────┴────────────────────────────┴────────────────────────┘
# ─────────────────────────────────────────────────────────────────────────────
TARGET_NUTRIENTS = {
    "Magnesium, Mg":                  "magnesium_mg",
    "Sugars, Total":                  "sugars_total_g",
    "Fatty acids, total saturated":   "saturated_fat_g",
    "Cholesterol":                    "cholesterol_mg",
    "Vitamin B-6":                    "vitamin_b6_mg",
    "Vitamin B-12":                   "vitamin_b12_mcg",
}
 
target_nutrient_names = list(TARGET_NUTRIENTS.keys())
 
# Build a lookup: fdc_id → {nutrient_name: amount}
nutrient_map = ( 
    food_nutrient.merge(nutrient_meta[["id", "name"]], left_on="nutrient_id", right_on="id") 
    .query("name in @target_nutrient_names") 
    [["fdc_id", "name", "amount"]] 
)
usda_pivot = nutrient_map.pivot_table(
    index="fdc_id", columns="name", values="amount", aggfunc="first"
).rename(columns=TARGET_NUTRIENTS)
 
# Category-level means (fallback for LOW-confidence matches)
# Step 1: attach USDA category to usda_pivot
usda_pivot_cat = usda_pivot.merge(
    usda[["fdc_id", "usda_category"]], on="fdc_id", how="left"
)
cat_means = usda_pivot_cat.groupby("usda_category")[list(TARGET_NUTRIENTS.values())].mean()
 
 
def borrow_values(best_links: pd.DataFrame, source_df: pd.DataFrame,
                  source_id_col: str) -> pd.DataFrame:
    """
    Add new nutrient columns to source_df by borrowing from USDA.
    Returns source_df with new columns appended.
    """
    out = source_df.copy()
    new_cols = list(TARGET_NUTRIENTS.values())
    for col in new_cols:
        out[col]                  = np.nan
        out[col + "_source"]      = "not_matched"   # provenance flag
        out[col + "_confidence"]  = np.nan
 
    for _, link_row in best_links.iterrows():
        src_id     = link_row["source_food_id"]
        fdc_id     = link_row["usda_fdc_id"]
        confidence = link_row["confidence"]
        usda_cat   = link_row["usda_category"]
        mask       = out[source_id_col] == src_id
 
        if confidence in ("HIGH", "MEDIUM"):
            # Food-level borrow: pull exact USDA values for this food
            if fdc_id in usda_pivot.index:
                for col in new_cols:
                    val = usda_pivot.loc[fdc_id, col] if col in usda_pivot.columns else np.nan
                    out.loc[mask, col] = val
                    out.loc[mask, col + "_source"]     = f"USDA_direct_{confidence.lower()}"
                    out.loc[mask, col + "_confidence"] = link_row["similarity_score"]
 
        else:  # LOW confidence → category mean
            if usda_cat in cat_means.index:
                for col in new_cols:
                    val = cat_means.loc[usda_cat, col] if col in cat_means.columns else np.nan
                    out.loc[mask, col] = val
                    out.loc[mask, col + "_source"]     = "USDA_category_mean"
                    out.loc[mask, col + "_confidence"] = link_row["similarity_score"]
 
    return out
 
print("\nBorrowing USDA values into TKPI ...")
tkpi_enriched  = borrow_values(tkpi_best,  tkpi,  "food_id")
print("Borrowing USDA values into MyFCD ...")
myfcd_enriched = borrow_values(myfcd_best, myfcd, "food_id")

Borrowing USDA values into TKPI ...
Borrowing USDA values into MyFCD ...

In [13]:
# ─────────────────────────────────────────────────────────────────────────────
# 8. SAVE OUTPUTS
# ─────────────────────────────────────────────────────────────────────────────
tkpi_best.to_csv( f"{OUTPUT_DIR}/tkpi_usda_links.csv",   index=False)
myfcd_best.to_csv(f"{OUTPUT_DIR}/myfcd_usda_links.csv",  index=False)
tkpi_enriched.to_csv( f"{OUTPUT_DIR}/tkpi_enriched.csv",  index=False)
myfcd_enriched.to_csv(f"{OUTPUT_DIR}/myfcd_enriched.csv", index=False)
print("\nOutputs saved:")
print("  tkpi_usda_links.csv   — linkage table")
print("  myfcd_usda_links.csv  — linkage table")
print("  tkpi_enriched.csv     — TKPI + 6 new USDA nutrient columns")
print("  myfcd_enriched.csv    — MyFCD + 6 new USDA nutrient columns")

Outputs saved:
  tkpi_usda_links.csv   — linkage table
  myfcd_usda_links.csv  — linkage table
  tkpi_enriched.csv     — TKPI + 6 new USDA nutrient columns
  myfcd_enriched.csv    — MyFCD + 6 new USDA nutrient columns

In [14]:
# ─────────────────────────────────────────────────────────────────────────────
# 9. QUICK VALIDATION — Kacang Arab (chickpea) example
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Validation: Kacang Arab (tkpi_0245) ===")
row = tkpi_enriched[tkpi_enriched["food_id"] == "tkpi_0245"]
new_cols = list(TARGET_NUTRIENTS.values())
src_cols = [c + "_source" for c in new_cols]
print(row[["food_id","food_name_normalized"] + new_cols + src_cols].T.to_string())

=== Validation: Kacang Arab (tkpi_0245) ===
                                                         244
food_id                                            tkpi_0245
food_name_normalized    kacang arab, kering (chick pea, raw)
magnesium_mg                                             NaN
sugars_total_g                                           NaN
saturated_fat_g                                          NaN
cholesterol_mg                                           NaN
vitamin_b6_mg                                            NaN
vitamin_b12_mcg                                          NaN
magnesium_mg_source                              not_matched
sugars_total_g_source                            not_matched
saturated_fat_g_source                           not_matched
cholesterol_mg_source                            not_matched
vitamin_b6_mg_source                             not_matched
vitamin_b12_mcg_source                           not_matched

In [15]:
# =============================================================================
# ---
# # THREE-WAY LINKAGE: TKPI ↔ MyFCD ↔ USDA
#
# Bagian ini adalah **tambahan** pada notebook asli. Tujuannya menghasilkan tabel
# linkage yang menghubungkan **TKPI dan MyFCD secara langsung**, dengan output utama
# berupa tiga kolom: `tkpi_food_id`, `myfcd_food_id`, `similarity_score`.
#
# Ada dua pendekatan yang disediakan:
#
# 1. **Direct matching (utama)** — mencocokkan nama pangan TKPI ↔ MyFCD secara langsung
#    menggunakan TF-IDF cosine dalam blok kelompok pangan yang sama. Lebih akurat karena
#    membandingkan nama SEA dengan nama SEA.
# 2. **USDA-bridge (cross-check)** — dua pangan yang tertaut ke `fdc_id` USDA yang sama
#    dianggap saling terkait secara transitif. Berguna sebagai validasi silang.
#
# Selain itu dihasilkan pula **non-match list**: pangan yang unik pada masing-masing
# basis data (tidak memiliki padanan di atas ambang).
# =============================================================================
 
# =============================================================================
# ## 10. Crosswalk Kelompok Pangan Bersama (TKPI ↔ MyFCD)
#
# TKPI dan MyFCD memakai taksonomi kategori yang berbeda. Agar dapat di-*blocking*
# secara langsung, kedua taksonomi dipetakan ke satu set **kelompok pangan bersama**
# (`_group`). Pemetaan ini konsisten dengan crosswalk ke USDA yang sudah ada.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 10. SHARED FOOD-GROUP CROSSWALK  (TKPI ↔ MyFCD direct blocking)
#     Map both regional taxonomies to a common coarse food group so that
#     TKPI and MyFCD items can be compared directly within the same block.
# ─────────────────────────────────────────────────────────────────────────────
TKPI_TO_GROUP = {
    "serealia":              "cereals",
    "umbi berpati":          "cereals",
    "sayuran":               "vegetables",
    "buah":                  "fruits",
    "daging":                "meat",
    "ikan/kerang/udang dll": "fish",
    "kacang-kacangan":       "legumes_nuts",
    "telur":                 "dairy_egg",
    "susu":                  "dairy_egg",
    "minyak/lemak":          "fats",
    "bumbu":                 "misc",
    "minuman non alkohol":   "beverages",
    "konfeksioneri":         "sweets",
}
 
MYFCD_TO_GROUP = {
    "cereals and grain products":         "cereals",
    "rice and rice flour based":          "cereals",
    "wheat flour based":                  "cereals",
    "cereal based":                       "cereals",
    "glutinous rice based":               "cereals",
    "porridge and ipengat/i":             "cereals",
    "starchy roots, tubers and products": "cereals",
    "tuber based":                        "cereals",
    "vegetables and vegetable products":  "vegetables",
    "vegetable dishes":                   "vegetables",
    "vegetables and fruits based":        "vegetables",
    "fruits and fruit products":          "fruits",
    "meat and meat products":             "meat",
    "meat dishes":                        "meat",
    "fish, shellfish and products":       "fish",
    "fish and sea-food dishes":           "fish",
    "legumes and legume products":        "legumes_nuts",
    "legume based":                       "legumes_nuts",
    "nuts, seeds and products":           "legumes_nuts",
    "eggs":                               "dairy_egg",
    "milk and milk products":             "dairy_egg",
    "oils and fats":                      "fats",
    "sugars and syrups":                  "sweets",
    "beverages":                          "beverages",
    "miscellaneous":                      "misc",
}
 
tkpi["_group"]  = tkpi["category_normalized"].map(TKPI_TO_GROUP)
myfcd["_group"] = myfcd["category_normalized"].map(MYFCD_TO_GROUP)
 
# Report any categories that failed to map (so you can extend the dicts)
unmapped_tkpi  = tkpi.loc[tkpi["_group"].isna(),  "category_normalized"].unique()
unmapped_myfcd = myfcd.loc[myfcd["_group"].isna(), "category_normalized"].unique()
if len(unmapped_tkpi):
    print("[warn] TKPI categories not mapped to a group:", list(unmapped_tkpi))
if len(unmapped_myfcd):
    print("[warn] MyFCD categories not mapped to a group:", list(unmapped_myfcd))
print("Shared groups present in both:",
      sorted(set(tkpi["_group"].dropna()) & set(myfcd["_group"].dropna())))

Shared groups present in both: ['beverages', 'cereals', 'dairy_egg', 'fats', 'fish', 'fruits', 'legumes_nuts', 'meat', 'misc', 'sweets', 'vegetables']

In [16]:
# =============================================================================
# ## 11. Direct TKPI ↔ MyFCD Matching (pendekatan utama)
#
# Menggunakan kembali `tfidf_cosine_match()` dari notebook asli, tetapi kini
# korpusnya adalah MyFCD (bukan USDA). Untuk setiap pangan TKPI dicari padanan
# MyFCD terbaik dalam blok kelompok yang sama.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 11. DIRECT TKPI ↔ MyFCD MATCHING
# ─────────────────────────────────────────────────────────────────────────────
def match_tkpi_to_myfcd(tkpi_df, myfcd_df, threshold=0.20, top_n=3):
    """
    For each TKPI food, find its top-n MyFCD matches within the same shared
    food group. Returns all pairs above threshold (long format).
    """
    all_links = []
    shared_groups = sorted(set(tkpi_df["_group"].dropna()) &
                           set(myfcd_df["_group"].dropna()))
    for grp in shared_groups:
        t_block = tkpi_df[tkpi_df["_group"] == grp]
        m_block = myfcd_df[myfcd_df["_group"] == grp]
        if t_block.empty or m_block.empty:
            continue
 
        q_names = t_block["name_norm"].tolist()
        c_names = m_block["name_norm"].tolist()
        c_ids   = m_block["food_id"].tolist()
        t_ids   = t_block["food_id"].tolist()
        t_orig  = t_block["food_name_normalized"].tolist()
 
        matches = tfidf_cosine_match(q_names, c_names, c_ids, top_n=top_n)
        for qi, myfcd_id, score in matches:
            if score < threshold:
                continue
            m_row = myfcd_df[myfcd_df["food_id"] == myfcd_id].iloc[0]
            all_links.append({
                "tkpi_food_id":     t_ids[qi],
                "tkpi_food_name":   t_orig[qi],
                "myfcd_food_id":    myfcd_id,
                "myfcd_food_name":  m_row["food_name_normalized"],
                "food_group":       grp,
                "similarity_score": round(score, 4),
            })
    return pd.DataFrame(all_links)
 
print("Matching TKPI ↔ MyFCD (direct) ...")
tm_links = match_tkpi_to_myfcd(tkpi, myfcd, threshold=0.20, top_n=3)
 
# Add confidence label (reuse classify_confidence from Cell 6)
tm_links["confidence"] = tm_links["similarity_score"].apply(classify_confidence)
 
# Keep the single best MyFCD match per TKPI food
tm_best = (tm_links
           .sort_values("similarity_score", ascending=False)
           .drop_duplicates("tkpi_food_id")
           .reset_index(drop=True))
 
print(f"\nTKPI foods with a MyFCD match: {tm_best['tkpi_food_id'].nunique()} / {len(tkpi)}")
print(f"Distinct MyFCD foods used:      {tm_best['myfcd_food_id'].nunique()} / {len(myfcd)}")
print("\nConfidence distribution:\n", tm_best["confidence"].value_counts())
tm_best.head(10)

Matching TKPI ↔ MyFCD (direct) ...

TKPI foods with a MyFCD match: 156 / 1146
Distinct MyFCD foods used:      55 / 234

Confidence distribution:
 confidence
LOW       124
MEDIUM     27
HIGH        5
Name: count, dtype: int64

,tkpi_food_id,tkpi_food_name,myfcd_food_id,myfcd_food_name,food_group,similarity_score,confidence
0,tkpi_1083,minyak kelapa (coconut oil),myfcd_0110,"oil, coconut (minyak kelapa)",fats,1.0000,HIGH
1,tkpi_0390,"bayam, segar (spinach, fresh)",myfcd_0228,"spinach, (bayam masak air)",vegetables,0.8102,HIGH
2,tkpi_0467,"jagung muda / semi, segar (baby corn, fresh)",myfcd_0035,baby corn (jagung sayur),vegetables,0.7385,HIGH
3,tkpi_0833,"rendang sapi, masakan",myfcd_0215,beef rendang (rendang daging lembu),meat,0.7022,HIGH
4,tkpi_1100,madu (honey),myfcd_0060,honey,sweets,0.6696,HIGH
5,tkpi_1080,"minyak ikan (fish, oil)",myfcd_0104,"fish oil, cod liver oil (minyak ikan kod)",fats,0.6422,MEDIUM
6,tkpi_0933,"kerang, segar",myfcd_0221,"cockles, boiled (kerang rebus)",fish,0.6407,MEDIUM
7,tkpi_0621,"buah naga merah, segar",myfcd_0040,"dragon fruit, red (buah naga, isi merah)",fruits,0.6122,MEDIUM
8,tkpi_0622,"buah naga putih, segar",myfcd_0041,"dragon fruit, white (buah naga, isi putih)",fruits,0.6112,MEDIUM
9,tkpi_0391,"bayam merah, segar (spinach, red, fresh)",myfcd_0228,"spinach, (bayam masak air)",vegetables,0.5893,MEDIUM

In [17]:
# =============================================================================
# ## 12. Tabel Linkage 3 Kolom (output yang diminta)
#
# Output inti: `tkpi_food_id`, `myfcd_food_id`, `similarity_score`.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 12. THREE-COLUMN LINKAGE TABLE
# ─────────────────────────────────────────────────────────────────────────────
tkpi_myfcd_links = tm_best[["tkpi_food_id", "myfcd_food_id", "similarity_score"]].copy()
 
print("tkpi_myfcd_links (3 kolom):", tkpi_myfcd_links.shape)
tkpi_myfcd_links.head(10)

tkpi_myfcd_links (3 kolom): (156, 3)

  tkpi_food_id myfcd_food_id  similarity_score
0    tkpi_1083    myfcd_0110            1.0000
1    tkpi_0390    myfcd_0228            0.8102
2    tkpi_0467    myfcd_0035            0.7385
3    tkpi_0833    myfcd_0215            0.7022
4    tkpi_1100    myfcd_0060            0.6696
5    tkpi_1080    myfcd_0104            0.6422
6    tkpi_0933    myfcd_0221            0.6407
7    tkpi_0621    myfcd_0040            0.6122
8    tkpi_0622    myfcd_0041            0.6112
9    tkpi_0391    myfcd_0228            0.5893

In [18]:
# =============================================================================
# ## 12b. (Opsional) Reciprocal / Mutual-Best Matching
#
# Pada tabel di atas, beberapa pangan TKPI dapat menunjuk ke pangan MyFCD yang sama
# (many-to-one). Untuk linkage berpresisi lebih tinggi, gunakan **mutual best match**:
# sepasang (TKPI, MyFCD) dipertahankan hanya jika MyFCD adalah padanan terbaik bagi
# TKPI **dan** sebaliknya TKPI adalah padanan terbaik bagi MyFCD. Ini menghasilkan
# tautan 1-1 yang lebih dapat dipercaya (cocok untuk pelaporan konservatif).
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 12b. RECIPROCAL (MUTUAL-BEST) MATCHING  — optional, higher precision
# ─────────────────────────────────────────────────────────────────────────────
# Best MyFCD match for each TKPI food (already computed: tm_best)
# Now compute best TKPI match for each MyFCD food (reverse direction).
def match_myfcd_to_tkpi(tkpi_df, myfcd_df, threshold=0.20, top_n=3):
    all_links = []
    shared_groups = sorted(set(tkpi_df["_group"].dropna()) &
                           set(myfcd_df["_group"].dropna()))
    for grp in shared_groups:
        t_block = tkpi_df[tkpi_df["_group"] == grp]
        m_block = myfcd_df[myfcd_df["_group"] == grp]
        if t_block.empty or m_block.empty:
            continue
        # queries = MyFCD, corpus = TKPI
        matches = tfidf_cosine_match(m_block["name_norm"].tolist(),
                                     t_block["name_norm"].tolist(),
                                     t_block["food_id"].tolist(), top_n=top_n)
        m_ids = m_block["food_id"].tolist()
        for qi, tkpi_id, score in matches:
            if score < threshold:
                continue
            all_links.append({"myfcd_food_id": m_ids[qi],
                              "tkpi_food_id": tkpi_id,
                              "similarity_score": round(score, 4)})
    return pd.DataFrame(all_links)
 
mt_links = match_myfcd_to_tkpi(tkpi, myfcd, threshold=0.20, top_n=3)
mt_best = (mt_links.sort_values("similarity_score", ascending=False)
           .drop_duplicates("myfcd_food_id"))
 
# Mutual-best: pairs that agree in both directions
fwd_pairs = set(zip(tm_best["tkpi_food_id"], tm_best["myfcd_food_id"]))
rev_pairs = set(zip(mt_best["tkpi_food_id"], mt_best["myfcd_food_id"]))
mutual = fwd_pairs & rev_pairs
 
tkpi_myfcd_links_mutual = (
    tm_best[tm_best.apply(lambda r: (r["tkpi_food_id"], r["myfcd_food_id"]) in mutual, axis=1)]
    [["tkpi_food_id", "myfcd_food_id", "similarity_score", "confidence"]]
    .reset_index(drop=True)
)
 
print(f"Mutual-best (1-1) links: {len(tkpi_myfcd_links_mutual)}")
print("Confidence distribution:\n", tkpi_myfcd_links_mutual["confidence"].value_counts())
tkpi_myfcd_links_mutual.head(10)

Mutual-best (1-1) links: 52
Confidence distribution:
 confidence
LOW       30
MEDIUM    17
HIGH       5
Name: count, dtype: int64

  tkpi_food_id myfcd_food_id  similarity_score confidence
0    tkpi_1083    myfcd_0110            1.0000       HIGH
1    tkpi_0390    myfcd_0228            0.8102       HIGH
2    tkpi_0467    myfcd_0035            0.7385       HIGH
3    tkpi_0833    myfcd_0215            0.7022       HIGH
4    tkpi_1100    myfcd_0060            0.6696       HIGH
5    tkpi_1080    myfcd_0104            0.6422     MEDIUM
6    tkpi_0933    myfcd_0221            0.6407     MEDIUM
7    tkpi_0621    myfcd_0040            0.6122     MEDIUM
8    tkpi_0622    myfcd_0041            0.6112     MEDIUM
9    tkpi_0259    myfcd_0030            0.5878     MEDIUM

In [19]:
# =============================================================================
# ## 13. USDA-Bridge Cross-Check (opsional)
#
# Dua pangan yang tertaut ke `fdc_id` USDA yang **sama** dianggap saling terkait
# secara transitif (TKPI → USDA ← MyFCD). Skor jembatan diambil sebagai nilai
# terkecil (paling konservatif) dari kedua skor tautan ke USDA.
#
# Ini berguna untuk memvalidasi pasangan hasil direct matching, atau menemukan
# pasangan tambahan yang mungkin terlewat.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 13. USDA-BRIDGE CROSS-CHECK  (transitive linkage via shared fdc_id)
# ─────────────────────────────────────────────────────────────────────────────
# tkpi_best / myfcd_best come from Cell 6 (best USDA match per source food).
bridge = tkpi_best[["source_food_id", "usda_fdc_id", "similarity_score"]].rename(
    columns={"source_food_id": "tkpi_food_id",
             "similarity_score": "tkpi_usda_score"}
).merge(
    myfcd_best[["source_food_id", "usda_fdc_id", "similarity_score"]].rename(
        columns={"source_food_id": "myfcd_food_id",
                 "similarity_score": "myfcd_usda_score"}),
    on="usda_fdc_id", how="inner"
)
 
# Bridge score = min of the two link scores (conservative)
bridge["bridge_score"] = bridge[["tkpi_usda_score", "myfcd_usda_score"]].min(axis=1)
bridge = (bridge
          .sort_values("bridge_score", ascending=False)
          .drop_duplicates(["tkpi_food_id", "myfcd_food_id"])
          .reset_index(drop=True))
 
print(f"USDA-bridge candidate pairs: {len(bridge)}")
print(f"Distinct TKPI foods bridged: {bridge['tkpi_food_id'].nunique()}")
 
# Cross-check: which direct matches are corroborated by the USDA bridge?
direct_pairs = set(zip(tkpi_myfcd_links["tkpi_food_id"],
                       tkpi_myfcd_links["myfcd_food_id"]))
bridge_pairs = set(zip(bridge["tkpi_food_id"], bridge["myfcd_food_id"]))
corroborated = direct_pairs & bridge_pairs
print(f"Direct matches also supported by USDA bridge: {len(corroborated)}")
 
bridge.head(10)

USDA-bridge candidate pairs: 51
Distinct TKPI foods bridged: 36
Direct matches also supported by USDA bridge: 24

,tkpi_food_id,usda_fdc_id,tkpi_usda_score,myfcd_food_id,myfcd_usda_score,bridge_score
0,tkpi_1100,169640,0.6298,myfcd_0060,1.0000,0.6298
1,tkpi_1083,171412,0.5625,myfcd_0110,0.5489,0.5489
2,tkpi_0426,169975,0.5036,myfcd_0225,0.5503,0.5036
3,tkpi_0391,168462,0.4611,myfcd_0228,0.4390,0.4390
4,tkpi_0390,168462,0.6364,myfcd_0228,0.4390,0.4390
5,tkpi_1079,173577,0.4136,myfcd_0104,0.6958,0.4136
6,tkpi_0163,170542,0.4047,myfcd_0024,0.3825,0.3825
7,tkpi_0463,170542,0.3847,myfcd_0024,0.3825,0.3825
8,tkpi_0460,170542,0.3940,myfcd_0024,0.3825,0.3825
9,tkpi_0166,170542,0.3949,myfcd_0024,0.3825,0.3825

In [20]:
# =============================================================================
# ## 14. Non-Match Lists (pangan unik per basis data)
#
# Pangan yang **tidak** memiliki padanan di atas ambang pada tabel direct linkage.
# Ini penting untuk narasi riset: item unik menunjukkan cakupan khas masing-masing
# basis data (mis. pangan lokal Indonesia yang tak ada padanannya di Malaysia).
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 14. NON-MATCH LISTS
# ─────────────────────────────────────────────────────────────────────────────
matched_tkpi_ids  = set(tkpi_myfcd_links["tkpi_food_id"])
matched_myfcd_ids = set(tkpi_myfcd_links["myfcd_food_id"])
 
tkpi_only = tkpi.loc[~tkpi["food_id"].isin(matched_tkpi_ids),
                     ["food_id", "food_name_original",
                      "category_normalized", "_group"]].copy()
myfcd_only = myfcd.loc[~myfcd["food_id"].isin(matched_myfcd_ids),
                       ["food_id", "food_name_original",
                        "category_normalized", "_group"]].copy()
 
tkpi_only  = tkpi_only.rename(columns={"food_id": "tkpi_food_id"})
myfcd_only = myfcd_only.rename(columns={"food_id": "myfcd_food_id"})
 
print(f"TKPI-only  (unique foods): {len(tkpi_only)} / {len(tkpi)}")
print(f"MyFCD-only (unique foods): {len(myfcd_only)} / {len(myfcd)}")
 
print("\nTKPI-only by group:\n",  tkpi_only["_group"].value_counts())
print("\nMyFCD-only by group:\n", myfcd_only["_group"].value_counts())
 
tkpi_only.head(10)

TKPI-only  (unique foods): 990 / 1146
MyFCD-only (unique foods): 179 / 234

TKPI-only by group:
 _group
vegetables      202
cereals         177
fish            163
legumes_nuts    128
fruits          124
meat            115
misc             32
dairy_egg        29
sweets           12
fats              7
beverages         1
Name: count, dtype: int64

MyFCD-only by group:
 _group
cereals         63
dairy_egg       27
misc            26
sweets          21
beverages       19
fats             8
vegetables       4
legumes_nuts     3
fruits           3
meat             3
fish             2
Name: count, dtype: int64

,tkpi_food_id,food_name_original,category_normalized,_group
7,tkpi_0008,"Beras ketan putih tumbuk, mentah (Glutinous ri...",serealia,cereals
10,tkpi_0011,"Beras parboiled (Rice, parboiled)",serealia,cereals
13,tkpi_0014,"Cantel, mentah (Sorghum, raw)",serealia,cereals
18,tkpi_0019,"Jali, mentah (Job's tear/adlay, raw)",serealia,cereals
19,tkpi_0020,"Jawawut, mentah (Italian millet, raw)",serealia,cereals
20,tkpi_0021,"Jampang huma, mentah (Ragi millet, raw)",serealia,cereals
22,tkpi_0023,Nasi tim,serealia,cereals
26,tkpi_0027,"Bihun, mentah",serealia,cereals
27,tkpi_0028,Bihun goreng instan,serealia,cereals
28,tkpi_0029,"Bihun Jagung, mentah",serealia,cereals

In [21]:
# =============================================================================
# ## 15. Simpan Output Three-Way
#
# Menyimpan tabel linkage 3 kolom, versi lengkapnya (dengan nama & confidence),
# jembatan USDA, dan kedua non-match list.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 15. SAVE THREE-WAY OUTPUTS
# ─────────────────────────────────────────────────────────────────────────────
# Core requested output: 3-column linkage table
tkpi_myfcd_links.to_csv(f"{OUTPUT_DIR}/tkpi_myfcd_links.csv", index=False)
tkpi_myfcd_links_mutual.to_csv(f"{OUTPUT_DIR}/tkpi_myfcd_links_mutual.csv", index=False)
 
# Detailed version (names + group + confidence) for auditing
tm_best.to_csv(f"{OUTPUT_DIR}/tkpi_myfcd_links_detailed.csv", index=False)
 
# USDA-bridge cross-check
bridge.to_csv(f"{OUTPUT_DIR}/tkpi_myfcd_bridge_via_usda.csv", index=False)
 
# Non-match lists
tkpi_only.to_csv(f"{OUTPUT_DIR}/tkpi_only_nonmatch.csv",  index=False)
myfcd_only.to_csv(f"{OUTPUT_DIR}/myfcd_only_nonmatch.csv", index=False)
 
print("Three-way outputs saved:")
print("  tkpi_myfcd_links.csv           — 3 kolom: tkpi_food_id, myfcd_food_id, similarity_score")
print("  tkpi_myfcd_links_detailed.csv  — versi lengkap (nama, grup, confidence)")
print("  tkpi_myfcd_bridge_via_usda.csv — cross-check jembatan USDA")
print("  tkpi_only_nonmatch.csv         — pangan unik TKPI")
print("  myfcd_only_nonmatch.csv        — pangan unik MyFCD")

Three-way outputs saved:
  tkpi_myfcd_links.csv           — 3 kolom: tkpi_food_id, myfcd_food_id, similarity_score
  tkpi_myfcd_links_detailed.csv  — versi lengkap (nama, grup, confidence)
  tkpi_myfcd_bridge_via_usda.csv — cross-check jembatan USDA
  tkpi_only_nonmatch.csv         — pangan unik TKPI
  myfcd_only_nonmatch.csv        — pangan unik MyFCD

In [22]:
# =============================================================================
# ## 16. Ringkasan Integrasi Tiga Basis Data
#
# Tabel ringkas status penautan untuk narasi Bab 3.
# =============================================================================
 
# ─────────────────────────────────────────────────────────────────────────────
# 16. INTEGRATION SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
summary = pd.DataFrame([
    {"pair": "TKPI → USDA",   "matched": tkpi_best["source_food_id"].nunique(),
     "total": len(tkpi),  "pct": round(100*tkpi_best["source_food_id"].nunique()/len(tkpi), 1)},
    {"pair": "MyFCD → USDA",  "matched": myfcd_best["source_food_id"].nunique(),
     "total": len(myfcd), "pct": round(100*myfcd_best["source_food_id"].nunique()/len(myfcd), 1)},
    {"pair": "TKPI ↔ MyFCD (direct)", "matched": tkpi_myfcd_links["tkpi_food_id"].nunique(),
     "total": len(tkpi),  "pct": round(100*tkpi_myfcd_links["tkpi_food_id"].nunique()/len(tkpi), 1)},
])
print("=== Integration summary ===")
print(summary.to_string(index=False))
 
print(f"\nTKPI-only (no MyFCD match):  {len(tkpi_only)}")
print(f"MyFCD-only (no TKPI match):  {len(myfcd_only)}")
print(f"USDA-bridge corroborated:    {len(corroborated)} direct pairs")

=== Integration summary ===
                 pair  matched  total  pct
          TKPI → USDA      334   1146 29.1
         MyFCD → USDA      138    234 59.0
TKPI ↔ MyFCD (direct)      156   1146 13.6

TKPI-only (no MyFCD match):  990
MyFCD-only (no TKPI match):  179
USDA-bridge corroborated:    24 direct pairs